### ISSUE TITLE
align legend handles by marker?

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#10]
Perhaps a question, perhaps a feature request. Is there any keyword to add to `legend` to align the labels by their marker? It seems like it auto-center-aligns by the whole object (marker + label).

E.g.: 

<img width="240" alt="screen shot 2019-02-21 at 11 23 17 am" src="https://user-images.githubusercontent.com/8881170/53192207-1b0d4b00-35cb-11e9-8502-6b214174c004.png">

I'd much prefer aesthetically if these things were left-aligned by the marker, so that the blue, red, and grey lines all line up.

**Comment by lukelbd** [comment]
Gonna take a guess at what happened here. In your plot commands were you using `h = ax.plot(...)` instead of `h, = ax.plot(...)`? Because `plot` always returns a tuple of line instances, even if you just used the command to plot one line. The second example pulls the handle out of the singleton tuple.

If you then thought you were making a list of handles `[h1, h2]`,  you were actually making a list of *lists* of handles. My legend function can optionally not align handles by column -- and it does this automatically when it detects a list of lists of handles instead of a list of handles (note you can override this by setting the `align` keyword arg manually).

P.S. I finally set up the documentation with sphinx (and made a cool logo); it's no longer on my personal website. Here's the [legend documentation](https://lukelbd.github.io/proplot/api/proplot.axes.legend_factory.html).

**Comment by lukelbd** [comment]
Alternatively, I totally spaced out and the default for the proplot version you were using was ``align=False`` lol.

**Comment by bradyrx** [comment]
Perfect, I didn't realize that about returning tuples. I'll now be assigning objects as `p, = ax.plot(...)`. That did the trick. Also I noticed the documentation -- that and the logo look great, will be digging into it. Also thanks for the shoutout!
