### ISSUE TITLE
Add back in Fabio Crameri's colormaps

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#115]
This is a reminder to add back in Fabio Crameri's colormaps per our discussion today @lukelbd. He just released v6 a few weeks ago: http://www.fabiocrameri.ch/colourmaps.php

**Comment by bradyrx** [comment]
I tried implementing this and am having trouble getting it registered. I added his `.xml` version which is identical as that of the SciVisColor ones to `proplot/cmaps`. I named them with a capital letter, e.g. `Acton.xml` and added them in `styletools.py` under a Fabio Crameri label. It's not getting registered when I do `show_cmaps()` or try to call it as a string in an example plot.

Am I missing something?

**Comment by lukelbd** [comment]
Not sure what the issue was (assuming you meant `.proplot`, not `proplot`). But #116 will add them back :). If you want them before the next release you can install the dev version as before (`pip install git+https://github.com/lukelbd/proplot.git`)

**Comment by bradyrx** [comment]
No I was trying to install them for a version release like you did, so I added them to the main directory and followed all conventions of the other colormaps. Not sure why it wasn't working still.

**Comment by lukelbd** [comment]
Any errors/warnings you can post, or was it silent (i.e. the files were just silently ignored)? Did you use e.g. `acton_QGIS.xml` or `acton_PARAVIEW.xml`? ProPlot can only read the latter file type, where the XML file contains `<Point> x="#" r="#" g="#" b="#" </Point>` tags (will document this in the future).

I ended up adding them to ProPlot using the `.txt` RGB files. ProPlot interprets all colormaps with `.txt` extension just like files with `.rgb` extension, so that something really simple like `cmap.save('colormap.txt')` doesn't throw an invalid filetype error (will add this to the [`from_file` documentation](https://proplot.readthedocs.io/en/latest/api/proplot.styletools.LinearSegmentedColormap.from_file.html) in the future).

Thanks for trying to contribute yourself, I appreciate that... probably should have just helped you work out the bugs rather than submitting my own PR.
