### ISSUE TITLE
Last longitude is not 0 when centered on 180°

### ISSUE THREAD

**Issue by mickaellalande** [lukelbd/proplot#118]
I have just noticed that in the lastest version the last longitude is not 0°, see example below (from what I remember this last value of longitude was not shown before):

```python
import proplot as plot
f, axs = plot.subplots(axwidth=4.5, proj='pcarree', proj_kw={'lon_0':180})

# Ordinary projection
axs.format(land=True, labels=True, lonlines=60, latlines=30)
axs[0].format(labels=True, title='Cartopy example')
```
![test](https://user-images.githubusercontent.com/20254164/73553402-3541e100-444a-11ea-8c8e-fad53c1c2c30.jpg)

Proplot version: 0.4.3

**Comment by lukelbd** [comment]
Sorry for the wait. This seems to be related to the [monkey patch](https://proplot.readthedocs.io/en/latest/changelog.html#proplot-v0-2-3-2019-12-05) we used to fix the overlapping-gridlines (I put this in a dedicated issue thread, #120). The patch permits gridliner labels on both edges of the projection by shifting the rightmost meridian location by a very small amount (`1e-10`)... which normally isn't picked up by the `LongitudeFormatter` (i.e. when converting `180 - 1e-10` to a nicely formatted string, it just rounds the number up)... but in this case since the location is `0` degrees, the offset *is* picked up by the formatter. Surprised this hasn't come up before.

I fixed this in 37fdd1eb by simply removing the meridian label from the right edge of the map. There seems to be no obvious way to keep it without this error.

This change is not yet in a release but can be found in the "development" version (use `pip install git+https://github.com/lukelbd/proplot.git`).
