### ISSUE TITLE
Issue plotting gx1v7 grid with "spstere" projection 

### ISSUE THREAD

**Issue by ZZephyrS** [lukelbd/proplot#125]
Issue: 
When plotting regional masks on a gx1v7 grid (POP) using proplot, the regions do not show up when using a polar projection. The same issue persists when just using `matplotlib` and when the masks are converted to a 180X360 grid. If I start using a 180x360 grid the problem does not arise. 

#### Code sample: see below

https://gist.github.com/ZZephyrS/0a76c0fa934b25c5c3fcb0fac7d3ef98

#### Actual result vs. expected result

Actual result: masked regions are not plotted when using a polar projection but they are plotted in a platte carree projection

Expected results: the regions are plotted regardless of the projection. 

<img width="1249" alt="Screen Shot 2020-02-27 at 3 39 43 PM" src="https://user-images.githubusercontent.com/43252611/75493568-6e04a580-5977-11ea-8a53-0f90c63c8181.png">

**Comment by lukelbd** [comment]
Thanks for the complete example -- unfortunately this wasn't a proplot/matplotlib issue but an issue with your dataset. What is actually happening is that matplotlib is drawing a giant white grid cell over the entire 0-360 longitude domain, underneath the gridlines and land masses. If you change cmap to something that is non-white bottom color (e.g. `cmap='viridis'`) you can see this even in the Plate Carrée example:


![test1](https://user-images.githubusercontent.com/19657652/75503135-0f98f080-5992-11ea-9974-8cb5a19228f3.png)


I think it just so happened that the matplotlib pcolormesh algorithm drew the white grid cell *before* (underneath) the colored ones in the Plate Carrée example, and *after* (on top of) the colored ones in the polar projection example.

Luckily, it looks like if you filter out the comparatively small values in your masks, e.g. with:

```python
threshold = 1.0
atl_mask_filtered = atl_mask.values.copy()
atl_mask_filtered[atl_mask_filtered < threshold] = np.nan
```

then this issue disappears:

![test2](https://user-images.githubusercontent.com/19657652/75503137-10318700-5992-11ea-903d-41ec3605e846.png)

**Comment by lukelbd** [comment]
Actually, it looks like a similar issue persists in *proplot* but not matplotlib:

![test3](https://user-images.githubusercontent.com/19657652/75503771-d95c7080-5993-11ea-93f8-ff735b2a64da.png)

You can fix it with e.g.:

```python
mask = atl_mask.values[:-1, :-1]
ax.pcolormesh(lon, lat, mask, ...)
```

![test4](https://user-images.githubusercontent.com/19657652/75503802-f42ee500-5993-11ea-80e9-a33861adb835.png)

When matplotlib's `pcolormesh` encounters pcolormesh coordinates with `N` x-coordinates, `M` y-coordinates, and an `M x N` data array, it simply *trims* the last row and column in your data array to make an `M - 1 x N - 1` array -- because the coordinates accepted by `pcolormesh` are supposed to represent the grid-cell *edges*, not centers.

Instead of trimming the last row and column, in this situation proplot tries to guess the correct graticule by taking averages of the coordinate vectors (see the last bullet point on [this page](https://proplot.readthedocs.io/en/latest/why.html#new-and-improved-plotting-methods), and [`edges2d`](https://proplot.readthedocs.io/en/latest/api/proplot.utils.edges2d.html), [`edges`](https://proplot.readthedocs.io/en/latest/api/proplot.utils.edges.html#proplot.utils.edges)). For your dataset, this also seems to mess up the `pcolormesh` algorithm.

However, when you have really high resolution data, this distinction doesn't really matter -- you can safely trim the mask edges and "pretend" your longitude-latitude coordinates are for the grid cell edges. In the future I might make this a configurable option, e.g. `trim_edges =True`.
