### ISSUE TITLE
There is an bug with using matplotlib after using proplot

### ISSUE THREAD

**Issue by ChamlamLeung** [lukelbd/proplot#132]
Hey guys. I met a problem today. 

I firstly ran the first codes with proplot package, and  got normal results. 
After that, I ran my second codes with matplotlib, however, the figure doesn't perform well.

The first codes are from [web](https://proplot.readthedocs.io/en/latest/subplots.html) :
`import proplot as plot
import numpy as np
N = 50
M = 40
state = np.random.RandomState(51423)
colors = plot.Colors('grays_r', M, left=0.1, right=0.8)
datas = []
for scale in (1, 3, 7, 0.2):
    data = scale * (state.rand(N, M) - 0.5).cumsum(axis=0)[N//2:, :]
    datas.append(data)
    
for share in (0, ):
    f, axs = plot.subplots(
        ncols=4, aspect=1, axwidth=1.2,
        sharey=share, spanx=share//2
    )
    for ax, data in zip(axs, datas):
        ax.plot(data, cycle=colors)
        ax.format(
            suptitle=f'Axis-sharing level: {share}, spanning labels {["off","on"][share//2]}',
            grid=False, xlabel='spanning', ylabel='shared'
        )`

It is ok with this figure.
![image](https://user-images.githubusercontent.com/33819977/76530329-8cf25400-64ae-11ea-97c4-1a5a823cf796.png)

My second codes are as followed:
`import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize=(6,2))
axes = fig.add_axes((0,0,0.8,1))
x = np.linspace(-10, 10, 1000)
line1, = axes.plot(x, np.sin(x))
axes.set_xlim((-10,10))  
axes.set_ylim((-2,2))  
axes.spines['right'].set_color('none')
axes.spines['top'].set_color('none')    
axes.xaxis.set_ticks_position('bottom')  
axes.yaxis.set_ticks_position('left')  
axes.spines['bottom'].set_position(('data', 1))   
axes.spines['left'].set_position(('data', 2))       
plt.show()`

Interestingly, the problem is here, it got the figure like this:
![image](https://user-images.githubusercontent.com/33819977/76530785-32a5c300-64af-11ea-96df-cd47e9b146ff.png)

If I restarted spyder and only ran the second codes, it performs well as followed. Then I ran the first codes and ran again the second codes after. There is still a problem. So it really confused me.
![image](https://user-images.githubusercontent.com/33819977/76531333-03dc1c80-64b0-11ea-8b5d-e975bdc02b65.png)

by the way,I ran my codes with spyder (version Spyder 4.0.1 ). I am not sure if it is my spyder problem or  because of the proplot.
Thanks.

**Comment by lukelbd** [comment]
I don't think this is a bug. The line

```python
axes = fig.add_axes((0,0,0.8,1))
```

draws the axes so it is flush against the bottom, left, and top sides. ProPlot just [changes the default matplotlib settings](https://matplotlib.org/tutorials/introductory/customizing.html) so that the backend uses gray for figure backgrounds drawn by the backend. If you save a figure with `savefig()` the background will be transparent, and save it with `savefig(transparent=False)` it will the background will be white. This will be explained in more detail in the docs in the next version.

If you want to use matplotlib default settings, you can use `plot.rc.style = 'default'` or put that in your `.proplotrc`.
