### ISSUE TITLE
Font and ticks thickness on Windows

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#134]
### Description
Fonts and ticks are too thin on Windows.
It seems the font follows the system fonts thickness.

### Steps to reproduce
I have tested this example on Linux and Windows:
```python
import proplot as plot
import numpy as np
import xarray as xr

plot.rc.fontname = 'TeX Gyre Heros'
times = np.arange(1990, 2000)
data = xr.DataArray(np.random.rand(len(times)), dims=['time'], coords=[times])

f, ax = plot.subplots(aspect=2)
ax.plot(data.time, data)
ax.format(xticks=np.arange(1990, 2000, 2))
f.savefig('test.png')
```

**Expected behavior**:
The output figure looks fine on Linux (`eog test.png`):
![Linux](https://user-images.githubusercontent.com/30388627/77130560-64acbb80-6a93-11ea-8b56-cedcff2cbc12.png)

**Actual behavior**:
But, if I run it on Windows or download that image from the Linux server, it looks too thin:
![image](https://user-images.githubusercontent.com/30388627/77130601-8a39c500-6a93-11ea-9ff2-5fb4206aee86.png)

### Font info
Here's the ouput of `plot.show_fonts()`:
**Linux**:
![image](https://user-images.githubusercontent.com/30388627/77130687-e4d32100-6a93-11ea-9438-4f7a491cd74e.png)

**Downloaded from Linux to Windows**
![image](https://user-images.githubusercontent.com/30388627/77130724-02a08600-6a94-11ea-92eb-ac5cc2614ba4.png)

**Windows**:
![image](https://user-images.githubusercontent.com/30388627/77130671-d553d800-6a93-11ea-8aab-6968ad954bff.png)

### Proplot version
0.5.0

**Comment by lukelbd** [comment]
Pretty sure this has to do with just matplotlib and your operating systems, not proplot. In the first example you posted, if you look closely, both the font *and* the axis ticks/spines are thicker.  So it has to do with rendering of the vector graphics in general, not just fonts. That seems to indicate either:

1. Differences in monitor resolution or different [figure backends](https://matplotlib.org/faq/usage_faq.html#what-is-a-backend) between the operating systems (if these are screenshots).
2. Differences in your [`InlineBackend.rc` settings](https://ipython.org/ipython-doc/2/config/options/notebook.html) (if you are using jupyter notebooks; try typing `%config InlineBackend`).
3. Different DPIs used to render the figure into a PNG format (try `from matplotlib import rcParams; print(rcParams['figure.dpi'], rcParams['savefig.dpi']`).

If you save the figures as *vector* graphics, e.g. `fig.savefig('test.pdf')` or `fig.savefig('test.eps')`, the fonts should 100% look identical. If they don't, this is probably a font rendering bug that should be submitted to matplotlib. Closing this issue since it's probably not a proplot bug but happy to help if you still have questions.
