### ISSUE TITLE
scatter colorbar ignores boundaries when outside of plot

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#144]
### Description

When using the `plt.scatter` wrapper, if some dimension of the data is mapped to color and the color bar placed externally, it is forced into a discrete colorbar and the boundaries cannot be modified. The colorbar features are different if placed *inside* the plot.

1. It would be great for this to generally be fixed.
2. Would it be feasible to add `levels` to the scatter wrapper?

### Steps to reproduce

```python
import numpy as np
import proplot as plot

state = np.random.RandomState(51423)
data = state.rand(2, 100)

f, ax = plot.subplots()
ax.scatter(*data, marker='o', color=data.sum(axis=0), cmap='Marine',
           colorbar='l', vmin=0, vmax=2,
           colorbar_kw={'boundaries': plot.arange(0, 2, 0.01),
                                  'locator': 0.5})

f, ax = plot.subplots()
ax.scatter(*data, marker='o', color=data.sum(axis=0), cmap='Marine',
           colorbar='lr', vmin=0, vmax=2,
           colorbar_kw={'boundaries': plot.arange(0, 2, 0.01),
                                  'locator': 0.5})
```

In the first bit, I am using `boundaries` as a hack to get at `levels`. I want to force this to much smaller colorbar steps, just to prove that it's working. It seems like `locator` works, but not `boundaries` for instance.

![Screen Shot 2020-04-22 at 2 53 20 PM](https://user-images.githubusercontent.com/8881170/80032892-12532600-84a9-11ea-9046-2ecbcc4f48be.png)

In the second bit, when `colorbar='lr'`, it works fine. I.e., when colorbars are inside the plot, the `boundaries` keyword works. When placed outside (e.g. `l`, `r`, `b`), the colorbar is funky.

![Screen Shot 2020-04-22 at 2 52 07 PM](https://user-images.githubusercontent.com/8881170/80032739-da4be300-84a8-11ea-8dcc-6ca2cf129306.png)

### Equivalent steps in matplotlib

The default exterior colorbar in `matplotlib` looks a lot better (it's continuous without mislabeling of the discrete boundaries), and the `boundaries` keyword works here.

```python
import matplotlib.pyplot as plt
state = np.random.RandomState(51423)
data = state.rand(2, 100)


f, ax = plt.subplots()
p = ax.scatter(*data, marker='o', c=data.sum(axis=0))

f.colorbar(p, boundaries=plot.arange(0, 2, 0.1))
```

![Screen Shot 2020-04-22 at 2 55 36 PM](https://user-images.githubusercontent.com/8881170/80033057-56dec180-84a9-11ea-89d9-505e625f8c19.png)

### Proplot version
0.5.0.post46

**Comment by lukelbd** [comment]
Thanks for the examples. Unfortunately it looks like this bug was introduced to the dev branch, possibly in commit f83570c3. Here is your first example with the last stable release (v0.5.0):

![bug_v5](https://user-images.githubusercontent.com/19657652/80034914-601d5d80-84ac-11ea-9117-088b6beb824d.png)

And here is the dev branch:

![bug_post46](https://user-images.githubusercontent.com/19657652/80034824-3fed9e80-84ac-11ea-8fb5-d156790606a6.png)

For now you can revert back to the last stable release.

**Comment by lukelbd** [comment]
Also I know the Issue page is getting pretty backed up here... I've been really focusing on research these past 2 months. Will try to catch up on these issues by the end of the month at least, then release a new version by early May.

**Comment by lukelbd** [comment]
Re: adding `levels` to scatter, I 100% support that. Right now it's a little complicated because `scatter` is wrapped by `cycle_changer`, and generally plotting functions are wrapped by *either* `cmap_changer` (which provides level support) *or* `cycle_changer`, not both.

This may be easier to do after #111 is merged, because then features can be added piecemeal to individual plotting methods like `Axes.contourf` and `Axes.scatter` by dispatching to several small, self-contained functions, instead of using these big honking wrapper functions like `cmap_changer`. The whole "wrapper function" idea is a relic of some of the very first plotting code I wrote for this library.
