### ISSUE TITLE
The alias "lw" doesn't work with histgram plot

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#186]
### Description

There are some issues with hist plots.
- lw doesn't work (linewidth does)
- When edgecolor is provided, no line is drawn unless linewidth is specified

### Steps to reproduce

```python
import numpy as np
import proplot as plot

x = np.random.randn(500)
fig, ax = plot.subplots()
ax.hist(x, lw=1)
```

**Expected behavior**: [What you expected to happen]
linewidth changes

**Actual behavior**: [What actually happened]
linewidth does not change

Also,
```
ax.hist(x, edgecolor='k')
```
does not draw line unless linewidth is specified

### Equivalent steps in matplotlib
```python
import numpy as np
import matplotlib.pyplot as plt

x = np.random.randn(500)
fig, ax = plt.subplots()
ax.hist(x, lw=1)
```
Also,
```
ax.hist(x, edgecolor='k')
```
### Proplot version

0.61

**Comment by lukelbd** [comment]
Thanks for the report:

* The `lw` issue was fixed in 0.6.3.
* The edgecolor issue is because a while ago, I added a line that sets the default histogram linewidth to zero (you are trying to change the color of zero-width line). But this had little justification and definitely should have been documented. Now, the default linewidth for histogram bars is the same as the default linewidth for normal bars and other matplotlib patches: `rcParams['patch.linewidth']`.

This is fixed on the master branch (https://github.com/lukelbd/proplot/commit/598214e1bffd8eb509ddd8c9efca641b15b2dbdc). You can install the master branch "version" with `pip install git+https://github.com/lukelbd/proplot.git`.
