### ISSUE TITLE
shadelabel = False cannot turn off the labels for shaded regions

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#187]
### Description

It would be better if there is an option to turn off the labels for shaded regions. When we plot many data at the same time, we usually want to show labels for the lines only and avoid having same labels for shaded regions.

I expect this to happen with `shadelabel=None` but it doesn't change anything. Can we fix this?

Or, it would be better if there is an option to combine label symbol of line and shaded region (which maybe too demanding).

Thanks always.

### Steps to reproduce

```python
import numpy as np
import pandas as pd
import proplot as plot

rng = np.random.default_rng()
x = rng.standard_normal((100, 10))
x = pd.DataFrame(x)
x.name = 'data'

fig, ax = plot.subplots()
ax.plot(x, means=True, shadepctiles=(5,95), legend='ll', shadelabel=None)
```

**Expected behavior**: [What you expected to happen]
Only show the label for the line

**Actual behavior**: [What actually happened]
The label for the shaded region still shows up.
![Screen Shot 2020-06-13 at 9 39 02](https://user-images.githubusercontent.com/61028484/84574205-b8106c00-ad59-11ea-9506-b624e2ffeaab.png)

### Proplot version

0.63

**Comment by lukelbd** [comment]
Agreed with all of your recommendations! Now, the default behavior is to draw shading underneath the line/marker in the legend entry. Otherwise, if you pass `shadelabel=True`, it adds separate legend entry with a *default* label. If you pass `shadelabel='label'`, it adds a separate legend entry with a *custom* label.

For example:

```python
import numpy as np
import pandas as pd
import proplot as plot

rng = np.random.default_rng()
x = rng.standard_normal((100, 10))
x = pd.DataFrame(x)
x.name = 'data'

fig, ax = plot.subplots()
ax.plot(x, means=True, shadepctiles=(5,95), legend='b')
# ax.plot(x, means=True, shadepctiles=(5,95), legend='b', shadelabel=True)
# ax.plot(x, means=True, shadepctiles=(5,95), legend='b', shadelabel='shading')
ax.format(title='Shading legend example')
```

![tmp](https://user-images.githubusercontent.com/19657652/84583534-8bd70880-adb6-11ea-8975-56e34c8a50ca.png)
![tmp1](https://user-images.githubusercontent.com/19657652/84583572-f0926300-adb6-11ea-9464-fb99538b81ec.png)
![tmp2](https://user-images.githubusercontent.com/19657652/84583571-eff9cc80-adb6-11ea-8353-0182b584e634.png)
