### ISSUE TITLE
error bars can't be modified

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#19]
@lukelbd, `proplot` suppresses error bar modification for some reason. I tried looking through the repo to see if `capsize`, `errorbar`, etc. was modified but it's rarely referenced. So must be something more internal you might have an idea of.

With  proplot:
```python
import proplot as plot
import numpy as np
x = ['A', 'B', 'C']
y = np.random.rand(3) * 10
err = np.random.rand(3)
f, ax = plot.subplots()
ax.bar(x, y, yerr=err, capsize=15)
```

<img width="230" alt="Screen Shot 2019-06-12 at 10 43 27 AM" src="https://user-images.githubusercontent.com/8881170/59370045-ef8ba900-8cfe-11e9-9811-7b1d42674e1f.png">

Without proplot:
```python
import matplotlib.pyplot as plt
import numpy as np
x = ['A', 'B', 'C']
y = np.random.rand(3) * 10
err = np.random.rand(3)
f, ax = plt.subplots()
ax.bar(x, y, yerr=err, capsize=15)
```

<img width="401" alt="Screen Shot 2019-06-12 at 10 44 09 AM" src="https://user-images.githubusercontent.com/8881170/59370089-07632d00-8cff-11e9-8e6b-b1b14c9c417b.png">

**Comment by lukelbd** [comment]
My clue was (1) that the problem appears in your pyplot example even if you just import proplot, but still use `pyplot.subplots`, and (2) [this thread](https://stackoverflow.com/a/49083686/4970632). Turns out the error bar "caps" are actually *marker* objects, whose line widths are controlled by the `markeredgewidth` property, which I set to `0` in the default `.proplotrc`. Certain types of markers have no "filled" component (e.g. `x`, `+`), so they become invisible when their "line width" is zero. This is pretty weird default behavior so I removed that line from the `.proplotrc` in 3094596.

Note from the [`bar` documentation](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.bar.html), it appears to change the width of the bar *and* whiskers, you need to use `ax.bar(...,  error_kw={'linewidth':3, 'markeredgewidth':3})`.
