### ISSUE TITLE
some of the subplots need map projection

### ISSUE THREAD

**Issue by miniufo** [lukelbd/proplot#211]
I would like two subplots.  The left subplot is plotted with a kwarg `proj='robin'` while the right one does not need `proj`.  This is sometimes common when the right plot is an (zonal) average of the left one.  See the example below:
![image](https://user-images.githubusercontent.com/9312831/89020350-562fb400-d351-11ea-956c-7d63e8ad05e9.png)

If I use the following code:
```python
fig, ax = pplt.subplots(ncols=2, nrows=1, proj='robin')
```
Two panels will both use `proj='robin'`.  So is it possible to have some of the subplots use `proj` and keep the rest use the default (non-projection) plot?

**Comment by mickaellalande** [comment]
Hi @miniufo, it looks actually possible. I don't know if it is well-formatted for these kinds of plots with projections, but so far here are two examples that I succeded to make (one with and without panels):

```python
import proplot as plot
import xarray as xr
da = xr.tutorial.open_dataset('air_temperature').air.mean('time') - 273.15
```
1) **Without panels** (see here for other examples: https://proplot.readthedocs.io/en/latest/projections.html)

```python
fig, axs = plot.subplots(nrows=1, ncols=2, proj=('cyl', None), wratios=(5, 1), axwidth=4)

# First axis
ax = axs[0]
m = ax.contourf(da, cmap='CoolWarm', symmetric=True)
ax.colorbar(m, label='Air Temperature [°C]', loc='b')

ax.format(
   title='Title 1', coast=True, labels=True, borders=True, lonlines=20, latlines=10,
   latlim=(da.lat.min().values, da.lat.max().values), lonlim=(da.lon.min().values, da.lon.max().values)
)

# Second axis
ax = axs[1]
ax.plot(da.mean('lon'), da.lat)
ax.format(title='Title 2', xlabel='°C', ylabel='latitude', ytickloc='right', yticklabelloc='right')

# Format all axs
axs.format(abc=True)
fig.save('panel_1.jpg', dpi=300)
```
![panel_1](https://user-images.githubusercontent.com/20254164/89034145-aa7a6a00-d338-11ea-91f8-def0469ff04f.jpg)


2) **With panels** (https://proplot.readthedocs.io/en/latest/insets_panels.html#Panel-axes)

```python
fig, axs = plot.subplots(nrows=1, ncols=1, proj='cyl', includepanels=True, axwidth=4)

# Plot
ax = axs[0]
ax.contourf(da, cmap='CoolWarm', symmetric=True, colorbar='b', colorbar_kw={'label': 'Air Temperature [°C]'} )

ax.format(
    title='Title 1', coast=True, labels=True, borders=True, lonlines=20, latlines=10,
    latlim=(da.lat.min().values, da.lat.max().values), lonlim=(da.lon.min().values, da.lon.max().values)  
)

# Panel
pax = ax.panel('r', width=0.8)
pax.plot(da.mean('lon'), da.lat)
pax.format(ylabel='latitude', title='Title 2')

# Format all axs
axs.format(abc=True)
fig.save('panel_2.jpg', dpi=300)
```
![panel_2](https://user-images.githubusercontent.com/20254164/89034150-ae0df100-d338-11ea-916e-a50911e23957.jpg)

Some small problems that I see:
- the latitudes are actually not exactly at the same level, maybe due to the projection or padding in the panels (I don't know if it is easy to fix this)? 
- the `xlabel` is not taken into account for the panels
- the option `abc=True` is not applied for the panel (I don't know if it is suitable or not), I guess you can add it manually with a left-title `ltitle` in the format

I guess @lukelbd that develop this package could answer better than me on these small issues. 

---
Proplot version: 0.6.4
Matplotlib version: 3.2.0

**Comment by miniufo** [comment]
Hi @mickaellalande  that is awesome!

I've tried `proj=('cyl', '')`, but didn't notice it should be `proj=('cyl', None)`.  Thanks very much for your examples.  I would like to follow the first one.

**Comment by zmoon92** [comment]
> Also want to know whether the first problem could be fixed:

>> the latitudes are actually not exactly at the same level, maybe due to the projection or padding in the panels (I don't know if it is easy to fix this)?


I think it is just because the y ax is not "tight". If you add `ax.autoscale(enable=True, axis="y", tight=True)` to the `#Second axis` block, they line up much better. Maybe there is a way to have ProPlot do that, though?

**Comment by lukelbd** [comment]
Hi @zmoon, the misalignment of panels A and B is related to #79, #178, #199.

Basically "axis sharing" is not possible between "geographic" plots  like in your example, because "axis sharing" doesn't make sense for a lot of non-rectangular projections, and projections often have longitude/latitude labels on the top/right of subplots (proplot currently doesn't support sharing of labels on the top/right). In the future I plan to support axis sharing for simple rectangular projections like Mercator and Plate Carrée (as in your example).

For now this issue duplicates those others, so I'll close it.
