### ISSUE TITLE
Passing 'fontsize' to format() has no effect on subplot font

### ISSUE THREAD

**Issue by miniufo** [lukelbd/proplot#212]
I have a plot of two panels, one with projection and one without:
![image](https://user-images.githubusercontent.com/9312831/89099095-7cbc2080-d41f-11ea-91fa-46bc7de29dfd.png)

I want to modify the tick label size of both panels.  It is possible to modify the font size in panel b (no projection) using `tick.labelsize` in `.proplotrc`.  But the lat/lon label size in panel a (with projection) cannot be changed accordingly.

I also wonder if there is a more convient way of changing font size in the single `format()` call, because `ax.format(fontsize=20)` seems not take any effect.

**Comment by lukelbd** [comment]
Hi @miniufo, you're right that `fontsize` (which represents the `rc['font.size']` property) should change the axes font when passed to `ax.format()`. It is sometimes unclear which rc settings can be updated with `format()`. I'll add this as a feature at some point.

For now you  have two options:

1. Change the default fontsize with e.g. `plot.rc['font.size'] = 6`. Note this will have an effect on all plot elements, both titles and labels, whose sizes are specified [relative to `font.size`](https://matplotlib.org/stable/api/font_manager_api.html#matplotlib.font_manager.FontProperties) with values like `'small'` and `'large'`).
1. Change both the geographic plot and cartesian plot label sizes with `axs.format(gridlabelsize=size, ticklabelsize=size)` or e.g. `plot.rc.update({'grid.labelsize': size, 'tick.labelsize': size})`.

**Comment by lukelbd** [comment]
This is now fixed. The fix was relatively simple, I just have to track which rc settings can have font size-relative values like `'small'` and `'large'` then update them whenever `rc['font.size']` is changed.

Below is an example. Note by default, just like matplotlib, proplot uses font size-relative units for all content.

![text](https://user-images.githubusercontent.com/19657652/124657483-c8f9b700-de5f-11eb-944f-88ac0b46ddcc.png)

**Comment by lukelbd** [comment]
(See 986347a)
