### ISSUE TITLE
Switch default docs to `stable`

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#220]
I suggest the default readthedocs landing page is `stable`, i.e. in line with the most recent release. Currently it defaults to `latest` which is in line with the `master` branch. I didn't recognize that and was having errors calling colormaps that didn't exist, for example.

**Comment by lukelbd** [comment]
Yeah this was not ideal... I saw your post but IIRC there were some annoying formatting issues with the latest stable docs due to an rtd-theme update that I didn't notice (notice the bleeding into the margins):

<img width="955" alt="Screen Shot 2021-06-29 at 7 55 14 PM" src="https://user-images.githubusercontent.com/19657652/123890219-1633d100-d914-11eb-902c-4146e18fe293.png">

But I think you're right `Stable` would have been better despite that issue. Just made it default -- I'm submitting a stable release with fixed formatting in the next few days anyway.

**Comment by lukelbd** [comment]
FYI I decided to add a deprecation system for renamed/removed colormaps: 22c0e35. So asking for e.g. `Blue1`, if it is not present in `CmapDict` as some user-defined map, redirects to `Blues1`.
