### ISSUE TITLE
Weird streaks with 2D ocean data

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#23]
Right now a 2D plot of ocean temperatures is making weird streaks with proplot, but works with matplotlib. Also, the right and bottom of the subplot get cut off.

You can download the sample data with:
```python
import climpred as cp
data = cp.tutorial.load_dataset('MPI-control-3D')
data = data.isel(time=0).tos
````

<img width="699" alt="Screen Shot 2019-07-05 at 12 25 10 PM" src="https://user-images.githubusercontent.com/8881170/60739674-1749e780-9f20-11e9-94a6-b17ba9c633ff.png">

Also a note to try out some of the climpred sample maps with proplot to see if these issues persist.

**Comment by lukelbd** [comment]
Fixing this one was completely crazy. It turns out that this artifact is actually related to your dataset and occurs in matplotlib normally, but cartopy **patches** that error in some complex and mysterious way, but I was doing something that ruined cartopy's patch. Try these examples after updating (the `s` is just to make the dataset smaller):

```python
import matplotlib.pyplot as plt
import proplot as plot
import climpred as cp
s = 2
# Load data
data = cp.tutorial.load_dataset('MPI-control-3D')
data = data.isel(time=0).tos
# Does not generate artifact
f, ax = plot.subplots(width=5, proj='pcarree', axcolorbar='r')
ax.pcolormesh(data.lon[::s,::s], data.lat[::s,::s], data[::s,::s], levels=20, colorbar='r')
# Basemap, generates artifact
# f, ax = plot.subplots(width=5, basemap=True, proj='pcarree', axcolorbar='r')
# ax.pcolormesh(data.lon[::s,::s], data.lat[::s,::s], data[::s,::s], levels=20, colorbar='r')
# On Cartesian axes/without projection, generates artifact
# f, ax = plot.subplots(width=5, axcolorbar='r')
# ax.pcolor(data.lon[::s,::s], data.lat[::s,::s], data[::s,::s], levels=20, colorbar='r')
# With pyplot, generates artifact
# f, ax = plt.subplots()
# ax.pcolor(data.lon[::s,::s], data.lat[::s,::s], data[::s,::s])
```

The cartopy patch evidently works by masking content in your data array. My `BinNorm` normalizer that I apply to all colormap objects was deleting/ignoring this mask (see the `ma.getmaskarray` lines in commit 222392e).

Also the latest ProPlot versions fix the weird font bug we came across the other day. It had to do with me adding a font `.ttf` file with a style unrecognized by matplotlib/that matplotlib interpreted as `'normal'`.

I also added your polar projection zoom-ins to [getting started](https://proplot.readthedocs.io/en/latest/quickstart4.html#zooming-into-projections), fixed a tight-layout bug that appeard with zoomed-in projections, fixed a bug related to the circular bounding box limits, fixed a bug where the `facecolor` attribute for map axes would get reset, and added the `'nplaea'`, `'splaea'`, `'npaeqd'`, and `'spaeqd'` projections to cartopy like in basemap.

Still just pushing to master at will.... will get into your workflow as I'm setting up CI with some smaller tests.

**Comment by lukelbd** [comment]
Also thanks for posting this issue. It definitely needed to be fixed and would probably have appeared mysteriously for various other users with various other datasets. I was exhausted when I posted this.

**Comment by bradyrx** [comment]
@lukelbd 
Awesome, thanks for all the updates here. So in summary, only use the cartopy projection format for these 2D maps? Looks like all the other options (including Basemap) generate those artifacts.

**Comment by lukelbd** [comment]
Yep that's right. My guess is it has to do with your data graticule crossing the edge of the map; cartopy takes pains to fix issues associated with stuff running over the map edge.

**Comment by bradyrx** [comment]
Having the Greenland-pole grid on the ocean always causes issues. With 2D lat/lon you can't really contour properly. I'm used to these problems, but they shouldn't occur on `pcolormesh`. Glad you were able to fix it!
