### ISSUE TITLE
proplot cannot draw clabels when using a cartopy projection. And cannot plot heatmap either. 

### ISSUE THREAD

**Issue by xiaochen30** [lukelbd/proplot#238]
### Description

proplot cannot draw clabels(contour labels) when using a cartopy projection. And cannot plot heatmap either.

### Steps to reproduce

```python
fig, axs = plot.subplots( axwidth=3.5,proj='cyl')
axs.contourf(var1, linewidth=1,cmap= cm.RdBu, labels=True,levels=np.linspace(-40,40,41), extend='both',zorder=-2)
axs.heatmap(var1, cmap= cm.RdBu,edgecolor='None',levels=np.linspace(-40,40,41),extend='both',zorder=-2)

```

**Expected behavior**: [What you expected to happen]

**Actual behavior**:    TypeError: 'NoneType' object is not iterable
                                    TypeError: format() got an unexpected keyword argument 'aspect'

### Equivalent steps in matplotlib

Please make sure this bug is related to a specific proplot feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
# your code here, if applicable
```

### Proplot version

0.6.4

**Comment by sfhua** [comment]
I met the same problem. Can anybody help us?

**Comment by pratiman-91** [comment]
Please explain what is `var1`?

**Comment by lukelbd** [comment]
Thanks @xiaochen30, this was a simple fix -- apparently `matplotlib.contour.ContourSet.clabel()` returns `None` if there are no contours (as is the case in your example).

As for the other issue, proplot's `heatmap` is only intended for cartesian axes. Internally, `heatmap` simply calls `pcolormesh` then sets the axes aspect ratio so that boxes look "square" and changes the default tick locations. None of this makes sense for polar plots or geographic plots. I now make that clear by having proplot emit a warning rather than an error.
