### ISSUE TITLE
Support polar axes labels with cartopy

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#246]
### Description

Now, cartopy has supported the axes labels for polar projection.

But, proplot doesn't work with the same newest version of cartopy.

### Steps to reproduce

```python
import proplot as plot
fig, axs = plot.subplots(proj='npstere')
axs.format(coast=True, latlines=10, lonlines=30, lonlabels=True, labels=True, boundinglat=60)
```

**Expected behavior** (matplotlib with cartopy)

![image](https://user-images.githubusercontent.com/30388627/109412029-c3d3b980-79e0-11eb-8783-e191b0983379.png)

**Actual behavior**: (proplot with cartopy)
![image](https://user-images.githubusercontent.com/30388627/109412047-cafac780-79e0-11eb-9d10-4b5881efba8e.png)

### Equivalent steps in matplotlib

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

ax = plt.subplot(projection=ccrs.NorthPolarStereo())
ax.set_extent([-180,180,90,60], ccrs.PlateCarree())
ax.coastlines()
ax.gridlines(draw_labels=True)
```

### Proplot version

0.6.4

**Comment by benjaminrichaud** [comment]
I have the same issue (using 'nplaea' projection). Considering that I am new to Proplot, I couldn't find where this lack of labels is coming from. I guess it should be somewhere around the '_toggle_gridliner_labels' method, but I can't find anything more. If someone can give me some hint of what to change, I am happy to participate in solving the bug, if that saves some time.

**Comment by lukelbd** [comment]
Finally figured this out. By default, proplot gives "pole-centered" projections [circle boundaries](https://proplot.readthedocs.io/en/latest/projections.html#Geographic-axes) to match basemap and because (IMHO) circle boundaries looks nicer. Unfortunately, however, cartopy does not seem to support gridline labels for maps whose boundaries were modified with [`set_boundary`](https://scitools.org.uk/cartopy/docs/latest/matplotlib/geoaxes.html#cartopy.mpl.geoaxes.GeoAxes.set_boundary).

So, this is a cartopy limitation -- when I repeat your example with a circular boundary the labels disappear:

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
ax = plt.subplot(projection=ccrs.NorthPolarStereo())
ax.set_extent([-180,180,90,60], ccrs.PlateCarree())
path = plot.axes.geo._circular_boundary(100)  # internal proplot method used to make polar boundaries
ax.set_boundary(path, transform=ax.transAxes)
ax.coastlines()
ax.gridlines(draw_labels=True)
plot.show()
```

![nolabels](https://user-images.githubusercontent.com/19657652/124370108-e7c63680-dc30-11eb-9e2f-b06a409f78b9.png)


However I recently decided to add the rc option `cartopy.circular` that can be set to `False` to disable the circle boundary thing. This will let you have labels on your polar plots (alternatively, you can also use `basemap` as the backend -- basemap supports labels on circular polar plots).

Here's an example with non-circular boundaries and gridline labels:


```python
import proplot as plot
plot.rc['cartopy.circular'] = False
fig, ax = plot.subplots(proj='npstere')
ax.format(coast=True, latlines=10, lonlines=30, lonlabels=True, labels=True, boundinglat=60)
```

I've added a note about this to the docs in the latest version.

**Comment by zxdawn** [comment]
@lukelbd Great! Thanks for coming back to polish proplot ;) Hope your Ph.D. career goes well.

**Comment by Thomas-Moore-Creative** [comment]
indeed, as said by @zxdawn - great to see you back @lukelbd, keeping proplot shiny!

**Comment by zxdawn** [comment]
@lukelbd The latitude grid labels aren't shown nicely.

If only one latitude label is shown, readers won't know the space between each latitude line.

```
import proplot as pplt
pplt.rc['cartopy.circular'] = False
fig, ax = pplt.subplots(proj='npstere')
ax.format(coast=True, latlines=10, latlabels=True, boundinglat=65)
```

![image](https://user-images.githubusercontent.com/30388627/130396503-6d71bee3-51d7-4efe-8c4a-9aedf8162127.png)

**Comment by lukelbd** [comment]
@zxdawn In this case you probably want `inlinelabels=True`. The new user guide [goes into more details](https://proplot.readthedocs.io/en/latest/projections.html#Formatting-projections) about different cartopy labelling options.

```python
 import proplot as plot
 plot.rc['cartopy.circular'] = False
 fig, ax = plot.subplots(proj='npstere')
 ax.format(coast=True, lonlabels=True, labels=True, boundinglat=60, inlinelabels=True)
```


![example](https://user-images.githubusercontent.com/19657652/130408843-a923088a-c98f-44c0-958c-1f0bb1e34510.png)

**Comment by zxdawn** [comment]
@lukelbd Wow, thanks for the new updates, Excellent!

**Comment by zxdawn** [comment]
@lukelbd Strange ... I tested it on my laptop with the master branch and also got the empty label image.

Here's the package info:
```
matplotlib: 3.4.3
cartopy: 0.20.1
```

For the inline and label, it still sounds confusing to me.
Let's take the image below as an example:
![image](https://user-images.githubusercontent.com/30388627/137555484-193dbd94-92c1-4342-b4fc-efb9c04edb0e.png)

How can I add lonlabels and enable only latinline, if they are the same?

**Comment by lukelbd** [comment]
Passing `ax.format(lonlabels=True, latinline=True)` means:

* Turn on longitude labels, but do nothing to the longitude label "inline mode". Note the "inline mode" is controlled with `rc['grid.inlinelabels']`. Its default value is `False`.
* Turn the latitude label "inline mode" to `True` -- and since this probably means you want to draw latitude labels, set `latlabels` to `True` as well. 

Here's an example with cartopy:

```python
pplt.rc['cartopy.circular'] = False
fig, ax = pplt.subplots(proj='npstere')
ax.format(coast=True, boundinglat=55, latlines=10, latinline=True, lonlabels='lrbt')
```

![tmp](https://user-images.githubusercontent.com/19657652/137559061-e34beed9-9475-4e8e-b864-f8dcfe6a8d8d.png)

**Comment by zxdawn** [comment]
Oh, I see. Thanks for the clarification.

Not sure what causes the result to be different from yours:
![image](https://user-images.githubusercontent.com/30388627/137559549-f1c9e0b5-a2fa-4c0b-a68b-2d7d63d88b50.png)

I will create a new environment later for test.

**Comment by zxdawn** [comment]
Yes, I got the same result when downgrading cartopy to v0.19.0.
