### ISSUE TITLE
Scientific notation colorbar

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#262]
### Description

Current version supports `axs.pcolormesh(data, norm='log')` to set the colorbar ticks to logscale.
However, the ticks can't be changed to scientific notation.

### Steps to reproduce

```python
import numpy as np
import proplot as plot
import matplotlib.ticker as ticker

# Sample data
N = 20
state = np.random.RandomState(51423)
data = 11 ** (0.25 * np.cumsum(state.rand(N, N), axis=0))

# Figure
fig, axs = plot.subplots()

# Plot with colormaps and normalizers
m = axs.pcolormesh(data, norm='log', cmap='viridis')
axs.colorbar([m])
```

**Expected behavior**:

Use `10^0, 10^1, 10^2, 10^3...` as the colorbar ticks.

**Actual behavior**:

Even if I follow the matplotlib tutorial [here](https://stackoverflow.com/questions/25983218/scientific-notation-colorbar-in-matplotlib):
```
def fmt(x, pos):
    a, b = '{:.1e}'.format(x).split('e')
    b = int(b)
    return r'${} \times 10^{{{}}}$'.format(a, b)

axs.colorbar([m], format=ticker.FuncFormatter(fmt))
```
The colorbar ticks aren't changed:
![image](https://user-images.githubusercontent.com/30388627/125589452-b0a11c68-d8fe-40eb-9eb0-130fedc3deea.png)

### Similiar steps in matplotlib

```python
import numpy as np
import matplotlib.ticker as ticker
import matplotlib.pyplot as plt

# Sample data
N = 20
state = np.random.RandomState(51423)
data = 11 ** (0.25 * np.cumsum(state.rand(N, N), axis=0))

# Figure
fig, axs = plt.subplots()

# Plot with colormaps and normalizers
m = axs.pcolormesh(data, cmap='viridis')

def fmt(x, pos):
    a, b = '{:.1e}'.format(x).split('e')
    b = int(b)
    return r'${} \times 10^{{{}}}$'.format(a, b)

plt.colorbar(m, format=ticker.FuncFormatter(fmt))
```

![image](https://user-images.githubusercontent.com/30388627/125589384-6846fa39-3a7c-46e8-af92-1863d6a46e33.png)

### Proplot version

0.7.0

**Comment by lukelbd** [comment]
Hi, this is a (somewhat hidden) proplot feature (see [this page](https://proplot.readthedocs.io/en/latest/axis.html#Tick-labels)). I make [`AutoFormatter`](https://proplot.readthedocs.io/en/latest/api/proplot.ticker.AutoFormatter.html#proplot.ticker.AutoFormatter) the default [tick label formatter](https://matplotlib.org/stable/gallery/ticks_and_spines/tick-formatters.html) everywhere, even in log-plots. This is because proplot's axis formatter trims trailing zeros so even in log-plots, the default formatter looks nice.

To change the colorbar formatter just pass `formatter='sci'` or `formatter='log'` to `colorbar` ([this page](https://proplot.readthedocs.io/en/latest/axis.html#Tick-labels)) from the docs shows all the available formatters). 

However I wasn't aware that matplotlib's `colorbar` functions already had a `format` keyword. I'll add that as an alias for `formatter` in the next version.

**Comment by lukelbd** [comment]
Just added that last note -- now `colorbar` will interpret the `format` keyword.

**Comment by zxdawn** [comment]
Thanks for the improvements👍
