### ISSUE TITLE
"Minor" longitude and latitude gridlines

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#27]
Is there any straight forward way to stride through what tick labels are shown in cartopy? Or could this be added as a feature?

This would be the equivalent of having `xticks=[0,5,10,15,20]` + `xticklabels=['0', '', '10', '', '20']` for instance. The idea here is especially in longitude when labels get packed and overlapped at a reasonable font size for folks to see.

```python
import numpy as np
import proplot as plot

plot.rc['geogrid.linestyle'] = ':'
plot.rc['geogrid.linewidth'] = 2
plot.rc['geogrid.color'] = '#d3d3d3'

data = np.random.rand(90, 180)
lon = np.linspace(-179.5, 179.5, 180)
lat = np.linspace(-89.5, 89.5, 90)

f, ax = plot.subplots(width='12cm', aspect=4, proj='cyl', tight=True,)

p = ax.pcolormesh(lon, lat, data, )

ax.format(latlim=(20,50), lonlim=(-135, -105), land=True,
          latlines=plot.arange(20,50,5), lonlines=plot.arange(-135,-105, 5),
          labels=True)

ax.colorbar(p, loc='r')
```

<img width="364" alt="Screen Shot 2019-08-28 at 2 06 45 PM" src="https://user-images.githubusercontent.com/8881170/63892769-3f444d00-c99d-11e9-856f-f3e9a8cfcf70.png">

This case doesn't have any issues, but imagine if you wanted the label size to be 14, 16, or 18 point font for a poster. All the lon labels overlap. **Any way to show just 130W, 120W, 110W but maintain the grid structure?** I figure there's a means to do it with the formatter/ticker, but I can't figure it out..

**Comment by lukelbd** [comment]
Makes sense to me -- having labeled and unlabeld gridlines would be analogous to having "major" and "minor" ticklines. You could do something like `lonlines=10` with `minorlonlines=5`. I'll implement it when I get the chance -- will just require drawing two gridliner objects.

**Comment by bradyrx** [comment]
FYI @lukelbd, it looks like the `minorlonlines` keyword is gone from `Axes.format`. And there is no `plot.rc.['gridminor.lonstep']` to access. I can't find any path forward to declare the minor grid line stepping/labeling in the current version.

**Comment by lukelbd** [comment]
Hmm not sure that was ever a feature. Can you point to a commit? For now you can do this manually using the [cartopy Gridliner](https://scitools.org.uk/cartopy/docs/v0.13/matplotlib/gridliner.html).

**Comment by bradyrx** [comment]
Oops I think I read your comment as if that was a hacky workaround with the current infrastructure.

**Comment by lukelbd** [comment]
This is now in the master branch. Cartographic gridline properties are now controlled with the `grid` and `gridminor` rc categories (`geogrid` has been deprecated -- the name will be translated and a warning will be issued when you try to use it).

Also, gridline location specs like `lonminorlines=X` and `lonlines=X` are now fully interpreted by `constructor.Locator()`, and formatter specs are interpreted by `constructor.Formatter()` -- this is done by linking them to dummy `_LonAxis` and `_LatAxis` axes that track the map extent in degrees longitude/latitude -- there is no longer a need for `lonstep` and `latstep` settings since the default `MaxNLocator` chooses appropriate intervals given the zoom level, just like with ordinary Cartesian plots. #167 really cleaned things up a lot.

Here's an example from the website:

```python
# %%
import proplot as plot
fig, axs = plot.subplots(
    [[1, 1, 2], [3, 3, 3]],
    axwidth=4, proj={1: 'eqearth', 2: 'ortho', 3: 'wintri'},
    wratios=(1, 1, 1.2), hratios=(1, 1.2),
)
axs.format(
    suptitle='Projection axes formatting demo',
    collabels=['Column 1', 'Column 2'],
    abc=True, abcstyle='A.', abcloc='ul', abcborder=False, linewidth=1.5
)

# Styling projections in different ways
ax = axs[0]
ax.format(
    title='Equal earth', land=True, landcolor='navy', facecolor='pale blue',
    coastcolor='gray5', borderscolor='gray5', innerborderscolor='gray5',
    gridlinewidth=1.5, gridcolor='gray5', gridalpha=0.5,
    gridminor=True, gridminorlinewidth=0.5,
    coast=True, borders=True, borderslinewidth=0.8,
)
ax = axs[1]
ax.format(
    title='Orthographic', reso='med', land=True, coast=True, latlines=10, lonlines=15,
    landcolor='mushroom', suptitle='Projection axes formatting demo',
    facecolor='petrol', coastcolor='charcoal', coastlinewidth=0.8, gridlinewidth=1
)
ax = axs[2]
ax.format(
    land=True, facecolor='ocean blue', landcolor='bisque', title='Winkel tripel',
    lonlines=60, latlines=15,
    gridlinewidth=0.8, gridminor=True, gridminorlinestyle=':',
)
```

![tmp](https://user-images.githubusercontent.com/19657652/82382686-a4d3e000-99e9-11ea-813d-c79426404f55.png)
