### ISSUE TITLE
`vmax` has no effects without `vmin`

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#276]
### Description

In the old version of proplot, once I set the `vmax`, the threshold of the plotting figure will change.

But I have to set both `vmin` and `vmax` to make it work for the new version.

### Steps to reproduce

```python
import proplot as pplt
import numpy as np

# Sample data
state = np.random.RandomState(51423)
x = y = np.array([-10, -5, 0, 5, 10])
data = state.rand(y.size, x.size)

# Figure
fig = pplt.figure(refwidth=2.3, share=False)
axs = fig.subplots()

m = axs.pcolormesh(x, y, data, vmax=1.35)
axs.colorbar([m], loc='r')
```

**Expected behavior**:
![image](https://user-images.githubusercontent.com/30388627/132112832-43fa58ed-7085-427e-b575-88599b54c278.png)

**Actual behavior**: [What actually happened]
![image](https://user-images.githubusercontent.com/30388627/132112841-25c22257-68ca-4ee0-9dd8-6a1626dda102.png)

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.
```
3.3.4
0.8.1
```

**Comment by lukelbd** [comment]
Thanks for the report, this was a very easy fix (0d345e2).

**Comment by zxdawn** [comment]
> @lukelbd This issue still exists in version 0.9.3:
> 
> ```
> import proplot as pplt
> import numpy as np
> 
> # Sample data
> state = np.random.RandomState(51423)
> x = y = np.array([-10, -5, 0, 5, 10])
> data = state.rand(y.size, x.size)
> 
> # Figure
> fig = pplt.figure(refwidth=2.3, share=False)
> axs = fig.subplots()
> 
> m = axs.pcolormesh(x, y, data, vmin=0, vmax=3)
> axs.colorbar([m], loc='r')
> ```
> 
> ![image](https://user-images.githubusercontent.com/30388627/136979608-e3f07403-348e-4918-9257-98e80a58b285.png)

@lukelbd I can reproduce the problem in `v0.9.5`.

**Comment by lukelbd** [comment]
Looks like I missed your last comment.

This actually isn't a bug -- it's a result of proplot feeding `vmin` and `vmax` into an algorithm similar to matplotlib's `_autolev` algorithm used to determine contour levels. The algorithm tries to generate nice levels and in general does not guarantee an exact match to `vmin` and `vmax` (the idea being that `vmin` and `vmax` are very often automatically chosen from the data (by default, or when using the `robust` keyword), and you don't want to have a discrete level boundary at e.g. `3.12349...`.

Although the behavior shown in your example is kind of silly, since `vmax=3` is obviously "nice" and shouldn't be truncated. Will take a look at the algorithm. Note that repeating your example with `discrete=False` results in an exact match, because "non-discrete" levels do not have to be ticked at vmin/vmax:

```python
import proplot as pplt
import numpy as np

# Sample data
state = np.random.RandomState(51423)
x = y = np.array([-10, -5, 0, 5, 10])
data = state.rand(y.size, x.size)

# Figure
fig = pplt.figure(refwidth=2.3, share=False)
axs = fig.subplots()

m = axs.pcolormesh(x, y, data, vmin=0, vmax=3)
axs.colorbar([m], loc='r')
```

![tmp](https://user-images.githubusercontent.com/19657652/150911854-ba9a13fd-7ed0-4c03-9f1e-b5d52191bbc0.png)
