### ISSUE TITLE
Duplicated legends when plotting hist of DataFrame

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#277]
### Description

When plotting the DataFrame hist, the legends are duplicated based on the bins. It should be one legend for one kind like the old version of proplot (0.7.0).

### Steps to reproduce

```python
import pandas as pd
import proplot as pplt

df = pd.DataFrame({
    'length': [1.5, 0.5, 1.2, 0.9, 3],
    'width': [0.7, 0.2, 0.15, 0.2, 1.1]
    }, index=['pig', 'rabbit', 'duck', 'chicken', 'horse'])

fig, axs = pplt.subplots()
axs.hist(df, bins=3)

axs.legend(ncols=1, loc='r')
```

**Expected behavior**:
![image](https://user-images.githubusercontent.com/30388627/132113210-f3a1d620-56b1-4bc8-9c0d-51f4d29a760d.png)

**Actual behavior**: [What actually happened]
![image](https://user-images.githubusercontent.com/30388627/132113216-f413a855-d680-4839-8dbf-e5e4ee8f96d8.png)

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.
```
3.3.4
0.8.1
```

**Comment by lukelbd** [comment]
This is now fixed (a871553). The issue: I was labelling every bar in the collection, rather than just the first one. 

P.S. In the latest proplot version "overlapped" histograms are no longer the default. Instead I use matplotlib's existing methods to bin/group 2D data. You can get "overlapped" histograms with `histtype='stepfilled'` or `filled=True`.

```python
import pandas as pd
import proplot as pplt

df = pd.DataFrame({
    'length': [1.5, 0.5, 1.2, 0.9, 3],
    'width': [0.7, 0.2, 0.15, 0.2, 1.1]
    }, index=['pig', 'rabbit', 'duck', 'chicken', 'horse'])

fig, axs = pplt.subplots()
axs.hist(df, bins=3)

axs.legend(ncols=1, loc='r')
```

![test](https://user-images.githubusercontent.com/19657652/132572355-a9075052-0334-4b81-9bef-c065e4c9d1cd.png)
