### ISSUE TITLE
Make layouting usable independent of other plotting features

### ISSUE THREAD

**Issue by matthias-k** [lukelbd/proplot#278]
### Description

I really like the proplot package! For me, by far the most important feature is the extremely powerful and flexibel way of aranging subplots in a figure by using units like inches instead of always having to compute in figure coordinates which change whenever any part of the figure changes.

However, I also have to use other plotting packages, most notably seaborn, which rely on many properties of matplotlib axes and plot objects. This is the reason why right now very often I can't use proplot although I would love to use it at least to layout my figure, or why at least I'm very hesitant to use proplot: changes are, some results down the line I have to port everything back to standard matplotlib just to be able to use some statistical plotting function that I need.

This brings me to my feature request: It would be absolutely awesome, if it would be possible to use `pplt.subplots` to create a figure and the subplots, but have all other features of proplot disabled or set to standard matplotlib behaviour (for example, by having subplots return standard matplotlib objects and have all config changes disabled). Then using proplot would be less of an all-or-nothing decision.

**Comment by lukelbd** [comment]
Really glad you find proplot useful!

This is definitely valid, but after thinking about it I'm leaning toward the alternative: inviting users to annoy me with 1000 bug reports, and we'll slowly plug away at them over time :). ProPlot is "supposed" to be mainly a _superset_ of matplotlib except in a few very limited cases (e.g. `legend` accepting lists of handles as a single positional argument). However, it does not entirely live up to that goal. Fixing bugs that crop up with external packages would be a win-win:

1. It would make the learning curve easier. If a developer writes matplotlib code that's incompatible with proplot, a new proplot user can do it too. This would help minimize backwards-incompatible changes and issue relevant warnings/gentle fallback behavior wherever incompatibilities appear (I try to do this already, but it's not systematic).
1. (As you said) It would let users invest in other packages, and take the pressure off of me to keep adding features. For example, while proplot overlaps with seaborn in several areas due to differing philosophies/design choices (e.g. "palettes" vs. colormaps/cycles and constructor functions), it would be silly of me to start replicating *all* of seaborn's plotting commands/behaviors in proplot, beyond the most basic stuff (e.g. kernel density plots, multicolor histograms). I'd like to support seaborn (maybe even include seaborn examples in the docs some day), but it's just a matter of limited time.

Also, by far the largest, most sweeping incompatibilities are related to geometry stuff, while the plotting commands can be close to 100% matplotlib-compatible if they just have more time to mature. So this would not necessarily solve all integration problems. And of course, this would require some pretty severe refactoring.

So, I'll close this issue for now and invite the bug reports instead, but let me know if you disagree with any of these points. Also, if you haven't yet, you should upgrade to v0.9 as it fixes some very basic/annoying seaborn integration issues (suppresses colormap re-registration warnings, fixes fatal bug related to "swarm plots" -- see #272).

**Comment by lukelbd** [comment]
Also, if the scope of the incompatibilities is larger/more intractable than I thought, we can definitely reopen.

**Comment by matthias-k** [comment]
@lukelbd I see your point. In this case, I'll happily open issues as I come across them :).
