### ISSUE TITLE
Assigning projections with projection dict. in subplots method

### ISSUE THREAD

**Issue by dopplerchase** [lukelbd/proplot#279]
### Description

Drawing custom subplot layout (one axis with Cartopy Proj, others with Cartesian) breaks with new version of proplot (> 0.6) 

### Steps to reproduce

Notebook to show where it breaks: https://colab.research.google.com/drive/1jlXYQTflOHVE-QxkEho7PFxfl8OyLZ13?usp=sharing 

**Expected behavior**: The first example in the notebook 

**Actual behavior**: breaks, does not plot 

### Equivalent steps in matplotlib

Not a way to do this in matplotlib, that's why I am using your package

### Proplot version
version < 0.6 works. > 0.6 breaks

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.
^I put these in the notebook

**Comment by lukelbd** [comment]
Thanks this was a quick fix. Btw `0` is always a pladeholder for "no axes here" so you don't need a `0: 'cartesian'` entry in the dictionary -- that will also raise an error. The Reason for this is why try to follow matplotlib's `add_subplot()` syntax -- e.g. `add_subplot(111)` adds a 1-row 1-column subplot to the first position rather than `add_subplot(110)`.

You can upgrade to the "dev" version with `pip install git+https://github.com/proplot/lukelbd`  or just use a list instead of a dictionary, e.g. `proj=['cyl', 'cart', 'cart', 'cart']`. Or use a `gs = pplt.GridSpec(ncols=2, nrows=6)` and add subplots one-by-one with `fig.subplot(gs[:2, 0], proj='cyl')`, `fig.subplot(gs[2:4, 0])`, `fig.subplot(gs[4:], 0)`, `fig.subplot(gs[1:5, 1])`.
