### ISSUE TITLE
Revert back to old "cyan", "yellow", "magenta"

### ISSUE THREAD

**Issue by matthias-k** [lukelbd/proplot#280]
### Description

It appears that since one of the recent releases of proplot, the color "cyan" has changed compared to the cyan color of default matplotlib

### Steps to reproduce

```python
import matplotlib.pyplot as plt

# first plot a cyan line with matplotlib
plt.plot([1,2], color='cyan')

# now import proplot and plot the cyan line again
import proplot as pplt
plt.plot([1,2], color='cyan')
```

**Expected behavior**: [What you expected to happen]

I would expect the two lines to have the same cyan color

**Actual behavior**: [What actually happened]

The line after importing proplot changed its color

![Screenshot_20210912_011228](https://user-images.githubusercontent.com/4093707/132965219-7db24367-0325-4104-895c-1feb177d9504.png)

![Screenshot_20210912_011313](https://user-images.githubusercontent.com/4093707/132965751-85c2108c-0817-490b-a1ff-79daec275527.png)

### Equivalent steps in matplotlib

see above

### Proplot version

* matplotlib: 3.4.2
* proplot: 0.9.0

**Comment by lukelbd** [comment]
Unfortunately this was intentional (see [What's New](https://proplot.readthedocs.io/en/latest/whatsnew.html#style-changes)). In matplotlib, the shorthand names `'y'`, `'c'`, and `'m'` are different from their full-length equivalents `'yellow'`, `'cyan'`, and `'magenta'` (see [this page](https://matplotlib.org/stable/gallery/color/named_colors.html)). I found this behavior strange, so a long long time ago, I added code to proplot meant to synchronize the shorthand and full-length names. However it was never implemented correctly -- in v0.9 I finally had time to fix it.

In retrospect, however, I definitely should have given this a second thought.... I can see the advantage of being able to easily switch between canonical "dark" and "light" versions of these otherwise very light colors. And the fact that `'yellow'` now gives us this very dark mustard yellow is probably even more counterintuitive than `'y'` and `'yellow'` resulting in different colors. And while proplot lets XKCD colors overwrite CSS colors (see the [table](https://proplot.readthedocs.io/en/v0.6.3/colors.html)), the new color is usually *somewhat* similar. However, the new `'magenta'`, `'yellow'`, and `'cyan'` are jarringly different, which is annoying for new users.

So, I think I'll revert back to the old behavior in the next version. I need to submit a quick bugfix release soon anyway, because Natural Earth changed their URLs, which broke older versions of cartopy and thus broke the geographic plot examples in the last stable version of the docs.

**Comment by lukelbd** [comment]
Sorry, didn't mean to close this.

**Comment by matthias-k** [comment]
Thanks for your answer! I see the elegance of having the color names unified, but in my opinion, compatibility with matplotlib is more important (as we also discussed in #278). At least with `rc['style'] = 'default'`, i.e. the default matplotlib stylesheet, I would expect the colors to match.

**Comment by lukelbd** [comment]
This is now implemented on master -- the basic red, blue, green, cyan, yellow, magenta are back to their CSS4 defaults.
