### ISSUE TITLE
Add geographic axes to panel plots

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#284]
### Description

Currently, `panel` does not accept the keyword `proj` to plot geographic plots.
I think it will be a useful feature when you want to show a small map on top of a hovmoller diagram. I can manually make a similar plot as follows, but it's a bit tedious and `abclabels` will be shown on all axes.

```python
slon=0
elon=360
proj = pplt.Proj('cyl', lon_0=180)

fig, axs = pplt.subplots(nrows=2, hratios=[1,6], proj=[proj, None])

axs[0].format(coast=True, latlim=(25, 65), lonlim=(slon, elon),
              labels=True, lonlabels='t')

axs[1].format(xformatter='deglon', xlim=(slon, elon),
              xlocator=60)
```

![Screen Shot 2021-09-17 at 14 43 59](https://user-images.githubusercontent.com/61028484/133856795-da1982bf-ae86-4a75-891c-c59b508d41fb.png)

**Comment by lukelbd** [comment]
Unfortunately I don't think I should implement this because it would involve a lot of special handling that would only benefit some pretty unusual use cases. The `panel_axes` infrastructure is built around the assumption that represent some reduced dimensionality of data on the main subplot, so it usually doesn't make sense to have a map projection panel.

I think what would make more sense in your case might be to make the *Hovmoller* plot the "panel" and make the projection the main subplot. You can make panels as large as you want -- nothing stopping you from having a narrow main subplot and a much larger panel. Here's an example:

```python
import proplot as pplt
slon=0
elon=360
proj = pplt.Proj('cyl', lon_0=180)
fig = pplt.figure()
ax = fig.subplot(
    proj=proj, land=True, abc='A.', title='Title', titleloc='l',
    latlim=(25, 85), lonlim=(slon, elon), labels=True, lonlabels='t'
)
px = ax.panel(
    'bottom', width=2, xformatter='deglon', share=False,
    xlim=(slon, elon), xlocator=60, number=2
)
N = M = 100
x = np.linspace(0, 360, N)
y = np.linspace(0, 25, M)
z = np.sin(x[:, None] / N + 20 * y[None, :] / N)
px.contourf(x, y, z, cmap='viridis')
```

![tmp](https://user-images.githubusercontent.com/19657652/150743738-8dfdbcca-5a66-4136-b75c-7d46a89cfa9a.png)

**Comment by lukelbd** [comment]
Also I realize one limitation of this is that you can't put colorbars along (e.g.) the left or right side of the Hovmoller plot, since it's a "panel".... but I think the generalization proposed in #329 will add support for this.
