### ISSUE TITLE
Pcolormesh shading

### ISSUE THREAD

**Issue by austin-hoover** [lukelbd/proplot#285]
### Description

The `pcolormesh` shading is different between Matplotlib and ProPlot figures. I'm wondering if anyone has come across this; I can't figure out what parameter is being changed. The issue doesn't show up for `imshow`. 

### Steps to reproduce

```python
import numpy as np
import matplotlib.pyplot as plt
import proplot as pplt

X = np.random.multivariate_normal(mean=[0., 0.], cov=[[1.0, 0.5], [0.5, 1.0]], size=100000)
lim = (-3.5, 3.5)
bins = 50
Z, xedges, yedges = np.histogram2d(X[:, 0], X[:, 1], bins, (lim, lim))

fig, ax = plt.subplots(figsize=(3, 3))
ax.pcolormesh(Z.T, cmap='dusk_r', shading='flat')
plt.show()

fig, ax = pplt.subplots(figsize=(3, 3))
ax.pcolormesh(Z.T, cmap='dusk_r', shading='flat')
plt.show()
```

![matplotlib](https://user-images.githubusercontent.com/58012334/133868425-9663b56b-a254-41fe-8830-82348e006ebf.png)
![proplot](https://user-images.githubusercontent.com/58012334/133868426-a82bb778-c3ff-4046-af36-d20ec10a2e1f.png)

Matplotlib version: 3.4.3
Proplot version: 0.9.1

**Comment by lukelbd** [comment]
Hi, this is a feature -- not a bug. Please see [the documentation section](https://proplot.readthedocs.io/en/latest/2dplots.html#Distinct-levels) on distinct levels and `DiscreteNorm`. I find it is very often useful to break colormaps into a subset of color levels like `contourf` rather than giving the perception of "smooth" color transitions, because it helps pick out numeric values in a colorbar.

Distinct levels can be turned off for particular `pcolor` plots by passing `discrete=False` to the plotting commands, or turned off persistently by setting `rc['cmap.discrete'] = False`.

**Comment by austin-hoover** [comment]
Ah, I missed that. Thanks for the help.
