### ISSUE TITLE
Colorbars on Projections may or may not work

### ISSUE THREAD

**Issue by natgeo-wong** [lukelbd/proplot#297]
Hi, I tried to plot colorbars on projections.  However, I'm getting different results on different computers.

On my work computer, I get a nicely-proportioned colorbar

![Ts_ERA5](https://user-images.githubusercontent.com/36907442/138165290-a44ea96e-9e29-4be5-bfea-0d6b6cec678a.png)

But on my home computer, I get a weirdly proportioned colorbar that indicates to me that the colorbar was plotted on the initial square (default aspect = 1) and then shrunk down.

![Tm_ERA5](https://user-images.githubusercontent.com/36907442/138165554-cf5c7d4e-bcbf-4f0f-980f-232fd82d804e.png)

I'm not too sure what is wrong here though.  I have proplot installed the same way on both my computers.

**Comment by natgeo-wong** [comment]
Hi!  This might be some issue with how Julia using Python.

I did a raw test on the actual python installation and it looks okay.  But it looks like somewhere in the pipeline where Julia calls Python (I use Julia for most of my work) we run into this problem.

**Comment by lukelbd** [comment]
Thanks for the update. Always cool to hear from people using proplot in Julia -- never imagined that was possible! In principle I think this is a legit issue though, since overcrowding / undercrowding of "discrete" colorbar ticks will always happen if the figure size changes after the colorbar is drawn.

I decided to fix this by introducing [`DiscreteLocator`](https://proplot.readthedocs.io/en/latest/api/proplot.ticker.DiscreteLocator.html?highlight=discretelocator). This is sort of like [`FixedLocator`](https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.FixedLocator) and  [`AutoLocator`](https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.AutoLocator) at once -- it selects from a *subset* of locations at the level boundaries depending on the axis size (see below examples). Previously, this only worked for static figure sizes, but now you can interactively resize a window and the ticks should auto-adjust.

Re-applying `extendsize` every time the figure size changes would be more complicated... and I suspect expensive. I'd have to redraw the entire colorbar solids with `Colorbar.draw_all()` every time. So I think I'll leave that alone for now and close this issue. Overlapping tick labels was definitely the more glaring problem in your example anyway.

```python
import proplot as pplt
levels = pplt.arange(0, 2, 0.1)
data = np.random.rand(5, 5) * 2
for width in (0.8, 1.2, 2):
    fig, axs = pplt.subplots(share=False, ncols=2, nrows=2, refwidth=width)
    for i, ax in enumerate(axs):
        cmd = ax.contourf if i // 2 == 0 else ax.pcolormesh
        m = cmd(data, levels=levels, extend='both')
        ax.colorbar(m, loc='t' if i // 2 == 0 else 'b')
        ax.colorbar(m, loc='l' if i % 2 == 0 else 'r')
```

![tmp0](https://user-images.githubusercontent.com/19657652/140000895-c6a5e014-c5ab-4179-899a-2ff47afbf017.png)

![tmp1](https://user-images.githubusercontent.com/19657652/140000898-b09966a2-73a3-4c22-9717-6d1b9b1f5012.png)

![tmp2](https://user-images.githubusercontent.com/19657652/140000901-fecea021-9a22-4864-aafb-e587bea82abe.png)
