### ISSUE TITLE
Legend label size not mutable by rcparams

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#3]
Calling ax.format(rc_kw={'legend.fontsize': int}) does not affect the font size of labels within the legend, and in fact overrides 'axes.labelsize', affecting the size of tick labels. However, other rcparams for the legend (e.g., legend.handlelength) do work. Because of this, I anticipate this is a `proplot` issue and not a `matplotlib` issue.

Sample code:
```
import numpy as np
import proplot as plot

def _set_aeshetics(ax):
    rc_kw = {'axes.labelsize': 8,
             'legend.fontsize': 20,
             'legend.handlelength': 6,
    }
    ax.format(rc_kw=rc_kw)

f, ax = plot.subplots(axwidth=6, aspect=5, bottomlegend=True)
x = np.random.rand(100,)
p = ax.plot(x, label='signal')
set_aeshetics(ax)
f.bottompanel.legend([p])
```

Note that 'legend.fontsize' doesn't affect the font size of labels within the legend, but actually blows up the tick labels to huge sizes. However, 'legend.handlelength' will stretch out the handle graphics.

---

Also, something internal to `proplot` blocks outside calls from managing this, e.g.:
```
plt.legend([p], prop={'size': 24})   
```

**Comment by lukelbd** [comment]
Thanks for the report. I'll look into that legend issue specifically, you should definitely be able to override the settings manually.

As for your first issue: in the `rcmod.py` file, there is a dictionary called `rcGlobals_children`:

```
rcGlobals_children = {
   # Important ones
   'xcolor':     [],
    'ycolor':     [],
    'color':      ['axes.labelcolor', 'axes.edgecolor', 'axes.hatchcolor', 'map.color', 'map.hatchcolor', 'xtick.color', 'ytick.color'], # change the 'color' of an axes
    'facecolor':  ['axes.facecolor', 'map.facecolor'], # simple alias
    'facehatch':  ['axes.facehatch', 'map.facehatch'], # optionally apply background hatching
    'small':      ['font.size', 'xtick.labelsize', 'ytick.labelsize', 'axes.labelsize', 'legend.fontsize'], # the 'small' fonts
    'large':      ['abc.fontsize', 'figure.titlesize', 'axes.titlesize'], # the 'large' fonts
    'linewidth':  ['axes.linewidth', 'map.linewidth', 'hatch.linewidth', 'axes.hatchlw',
                   'map.hatchlw', 'xtick.major.width', 'ytick.major.width'], # gridline widths same as tick widths
                   # 'grid.linewidth', # should not be coupled, looks ugly
    'gridalpha':  ['grid.alpha',     'gridminor.alpha'],
    'gridcolor':  ['grid.color',     'gridminor.color'],
    'gridstyle':  ['grid.linestyle', 'gridminor.linestyle'],
    # Aliases
    'margin':         ['axes.xmargin', 'axes.ymargin'],
    'xmargin':        ['axes.xmargin'], # found I wanted to change these *a lot*
    'ymargin':        ['axes.ymargin'], # found I wanted to change these *a lot*
    'fontname':       ['font.family'], # specify family directly, so we can easily switch between serif/sans-serif; requires text.usetex = False; see below
    'abcweight':      ['abc.weight'],
    'titleweight':    ['axes.titleweight'],
    'suptitleweight': ['figure.titleweight'],
    # Less important ones
    'bottom':     ['xtick.major.bottom',  'xtick.minor.bottom'], # major and minor ticks should always be in the same place
    'top':        ['xtick.major.top',     'xtick.minor.top'],
    'left':       ['ytick.major.left',    'ytick.minor.left'],
    'right':      ['ytick.major.right',   'ytick.minor.right'],
    'ticklen' :   ['xtick.major.size',    'ytick.major.size'],
    'tickdir':    ['xtick.direction',     'ytick.direction'],
    'tickpad':    ['xtick.major.pad', 'xtick.minor.pad', 'ytick.major.pad', 'ytick.minor.pad'],
    }
```

The basic idea here is, the user could change a *global* property (the dictionary keys) to change any of the constituent ("children") properties all at once. This includes the key `"small"` for axis labels, tick labels, legend text, colorbar label text, and text manually added with `ax.text()`, and the key `"large"` for axes titles, "super" figure titles, and the "abc" labelling. (Note a few items in those dictionary lists, like `abc.fontsize`, are new `rc` items I made up, stored not in `mpl.rcParams` but in a separate custom dictionary.) This is based on my (possibly biased) opinion of which font sizes in a figure "should" be about the same.

The problem is, whenever you change a setting in one of these "property families", all the other settings get changed too. Since in your example dictionary, `legend.fontsize` comes after `axes.labelsize`, it's the one that gets applied to the entire family.

I think *I'll disable this behavior*, and make the "property syncing" only possible when the user accesses those global keywords `"small"`, `"large"`, etc. I suppose it is pretty unexpected behavior when you're just starting to use this repo (exhibit A: this issue).

Note the `small` and `large` sizes can be changed a number of ways: `font.rc.small = <num>`, `font.rc['small'] = <num>`, `ax.format(small=<num>)`, or `ax.format(rc_kw={'small':num})`, and same for `"large"`.

**Comment by bradyrx** [comment]
@lukelbd  Thanks for thinking about this. I've always found rcParams to be powerful but inconsistent. The best method for me has been to make my own style file, but then it's sort of a fixed style.

I like the `set_aesthetics` method, since it can just be called once. Do you have any other suggestions for how to go about doing this, or do you agree that a quick function call works well?

**Comment by bradyrx** [comment]
@lukelbd, I gave the global approach a shot and still 'small' doesn't affect the legend.fontsize feature. It seems like a larger lock on legend mutability for some reason.

---

`no formatting change`
<img width="568" alt="screen shot 2019-01-15 at 6 05 44 pm" src="https://user-images.githubusercontent.com/8881170/51219902-314f2980-18f0-11e9-9f55-8b29c52478a2.png">

`ax.format(rc_kw={'small': 14})`
<img width="567" alt="screen shot 2019-01-15 at 6 04 57 pm" src="https://user-images.githubusercontent.com/8881170/51219868-154b8800-18f0-11e9-99c2-d586e17a73ef.png">

**Comment by bradyrx** [comment]
Great, thanks for that fix! This should work fine for now. Two other oddities to point your attention to:

1. One has to run the `plot.rc['legend.fontsize']` prior to calling the legend for it to take affect, while other rcParams are indifferent to this order. Perhaps it is just good practice anyways to do the rcParams first thing in a figure.

```python
import proplot as plot
import numpy as np
plot.nbsetup()
x = np.random.rand(100,)
f, ax = plot.subplots(nrows=2, axwidth=6, aspect=5)
ax[0].plot(x, label='data')
ax[0].legend()
ax.format(rc_kw={'small': 14})
ax[1].plot(x, label='data')
ax[1].legend()
```

2. Not all y tick labels seem to pick up on rcParam edits (see below figure rendered from above code). I've noticed this from time to time while making plots. More commonly it's just the upper end (like in the top plot), but for some reason a portion of y ticks remain small.

<img width="657" alt="screen shot 2019-01-15 at 10 00 06 pm" src="https://user-images.githubusercontent.com/8881170/51227364-23f66700-1911-11e9-8492-9770a713d36d.png">

**Comment by bradyrx** [comment]
Fixed it on my end! Thanks. Will keep you posted on other issues; doing plenty of plotting lately so giving you some rigorous testing.
