### ISSUE TITLE
ax.set_zorder not working

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#303]
### Description

`ax.set_zorder` does not work in `proplot`.
This becomes an issue when we want to change the zorders of `twinx` axes.

### Steps to reproduce

```python
import numpy as np
import pandas as pd
import proplot as pplt

x = np.linspace(0, 2*np.pi, 100)

fig, ax1 = pplt.subplots()
ax1.plot(np.sin(x), lw=3, c='b')

ax2 = ax1.twinx()
ax2.plot(np.sin(2*x), lw=3, c='r')

ax1.set_zorder(ax2.get_zorder()+1)
ax1.patch.set_visible(False)
```

**Expected behavior**: [What you expected to happen]
Red line to be placed beneath the blue line

**Actual behavior**: [What actually happened]
![Screen Shot 2021-11-29 at 17 59 30](https://user-images.githubusercontent.com/61028484/143972019-5f525c92-0353-4d7d-8634-46cf295a4414.png)

### Equivalent steps in matplotlib

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 100)

fig, ax1 = plt.subplots()
ax1.plot(np.sin(x), lw=3, c='b')

ax2 = ax1.twinx()
ax2.plot(np.sin(2*x), lw=3, c='r')

ax1.set_zorder(ax2.get_zorder()+1)
ax1.patch.set_visible(False)
```
![Screen Shot 2021-11-29 at 18 01 00](https://user-images.githubusercontent.com/61028484/143972173-c24cbd67-6690-456d-9b36-80ab118460e3.png)

### Proplot version
3.4.3
0.9.4

**Comment by lukelbd** [comment]
It seems this is because (unlike matplotlib) proplot implements twin axes as "children" of the original axes rather than separate figure axes. This approach simplifies the tight layout algorithm, but means that the drawing order of the twin axes is controlled by the zorder of content *inside* the original axes rather than the original axes itself. So in principle, you should just need to set `zorder` below that of the blue line with e.g. `ax1.twinx(zorder=1)` (see below). I should have explained this in the documentation -- will add a disclaimer.

Your example also directed me to a bug -- `zorder=1` only works in matplotlib < 3.4. In matplotlib >= 3.4, it seems the twin axes is getting drawn *twice*, once as a "child" of the original axes and once as a separate figure axes. So, for your purposes you need to use `zorder=-1` instead. I'll fix this in the next version.

```python
import numpy as np
import proplot as pplt

x = np.linspace(0, 2*np.pi, 100)

fig, ax1 = pplt.subplots()  # axes with default zorder 0
ax1.plot(np.sin(x), lw=3, c='b')  # line with default zorder 2
ax2 = ax1.twinx(zorder=1)  # less than the line, more than the subplot
ax2.plot(np.sin(2*x), lw=3, c='r')
```

![empty](https://user-images.githubusercontent.com/19657652/144122711-bb3c1fee-250e-4e89-a392-056ebb446870.png)

**Comment by lukelbd** [comment]
This is now fixed -- you should get the above result in matplotlib 3.4+, and I've added a disclaimer to the documentation noting the different `zorder` behavior [here](https://proplot.readthedocs.io/en/latest/cartesian.html#Alternate-axes).
