### ISSUE TITLE
Duplicated tick label of colorbar

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#304]
### Description

Sometimes there're duplicated ticks shown on the colorbar.

### Steps to reproduce

```python
fig, axs = pplt.subplots()
import numpy as np

Z = np.random.rand(5, 5)*3
m = axs.pcolormesh(Z, cmap='viridis', levels=256, vmin=0, vmax=3)
axs.colorbar(m, ticks=0.25)
```

**Expected behavior**: [What you expected to happen]
The label of `2` tick shouldn't be overlayed with `2.25`

**Actual behavior**: [What actually happened]
![image](https://user-images.githubusercontent.com/30388627/144219883-5e89fe6c-9412-42a4-9a64-33b910e924eb.png)

### Proplot version

```
matplotlib: 3.5.0
proplot: 0.9.5.post78
```

**Comment by lukelbd** [comment]
Sorry, I fixed an issue related to #303 (where outer colorbars are getting drawn twice) and thought that was the problem here. But, the problem is still present. I think it's actually related to the `DiscreteLocator` used with "discrete" `levels` -- if you use `discrete=False` instead of `levels=256` the issue goes away (see [this section](https://proplot.readthedocs.io/en/latest/2dplots.html#Discrete-levels) of the docs -- note that in general, if you just want "smooth" levels, using `discrete=False` will give a faster rendering time than modifying `levels`).

**Comment by lukelbd** [comment]
After further investigation, it seems this is unrelated to `DiscreteLocator` -- it's a matplotlib 3.5+ bug related to "discrete" normalizers like matplotlib's `BoundaryNorm` and proplot's `DiscreteNorm`. Version 3.5 completely overhauls the colorbar ticking internals so this isn't too surprising.

Here's an example with matplotlib only that reproduces the issue (not sure how to fix the messed up color scale -- `norm.vmax = 3` does nothing and passing `vmax=3` to `BoundaryNorm` raises an error -- but that's not relevant). This problem also seems to be independent from the number of "boundaries".  If you have time feel free to start a matplotlib issue with this example.

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.ticker as mticker
fig, ax = plt.subplots()
edges = np.linspace(0, 3, 10)
norm = mcolors.BoundaryNorm(edges, 1000)
Z = np.random.rand(5, 5) * 3
m = ax.pcolormesh(Z, cmap='viridis', norm=norm)
cb = fig.colorbar(m, ticks=mticker.MultipleLocator(0.25))
fig.show()
```

![tmp](https://user-images.githubusercontent.com/19657652/144333675-15dab18c-0b15-48c1-9c1e-3b4b2d0b93f5.png)

**Comment by zxdawn** [comment]
Thanks for the debug. Submitted the [issue](https://github.com/matplotlib/matplotlib/issues/21841) to matplotlib.
