### ISSUE TITLE
Something wrong with italic fonts?

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#318]
### Description

I was trying to display mathematical texts (specifically `alpha`) with the matplotlib-supplied fonts but I couldn't do it by setting `pplt.rc['font.family'] = 'DejaVu Sans'` and `pplt.rc['mathtext.default'] = 'it'`. Am I missing something here?

Aside from this behavior, personally, the default greek letters in proplot are not so pleasing. `'Fira Math'` looks better but it isn't so pleasing when the italic font is used (as shown below). Can we improve this?

### Steps to reproduce

When italic font is selected, all alpha look the same. Is this the expected behavior?
```python
import proplot as pplt
pplt.rc['mathtext.default'] = 'it'
fig, axs = pplt.show_fonts()
```
![pplt_font_it](https://user-images.githubusercontent.com/61028484/147995149-1c0134f2-08a6-4a8a-a360-100bcc6eb41b.png)

The above italic font in `'DejaVu Sans'` looks different from the one in matplotlib. 
```python
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = 18

fig, ax = plt.subplots()

ax.text(.2, .9, 'regular')
ax.text(.6, .9, 'italic')

ax.text(.3, .7, r'$\mathrm{\alpha}$')
ax.text(.7, .7, r'$\alpha$')
```
![plt_font](https://user-images.githubusercontent.com/61028484/147994407-e5178cd5-365f-477e-8ac9-6d6933056b2a.png)

### Proplot version
3.4.3
0.9.5

**Comment by lukelbd** [comment]
Weird..... not sure why the Greek italic letters are identical. I also tested with `show_fonts(style='italic')` and the Latin italic letters are all different as expected -- it's just the Greek math letters that are the same. And agree that the default non-italic alphas look strange. Will look into this.

**Comment by lukelbd** [comment]
Oh never mind... what's happening is when `rc['mathtext.default'] = 'regular'` (the default after importing proplot), matplotlib uses the same font inside an `$equation$` as it does for normal text (see [these lines](https://github.com/matplotlib/matplotlib/blob/a76e037c32c2f7981410ed29c22b4ca4d48e080d/lib/matplotlib/mpl-data/matplotlibrc#L328-L349)). When you set `rc['mathtext.default'] = 'it'`, that applies the italic version of `rc['mathtext.fontset']` (default value `'dejavusans'`) to all math text. So, that's why the font demo shows the same math in each line, and it *should* be DejaVu Sans-rendered math.

However, I'm not sure why your example with `rc['mathtext.default'] = 'it'` in matplotlib is different from your example in proplot. I got the below results, first without then with proplot:

```python
import matplotlib.pyplot as plt
# import proplot as pplt  # uncomment for second run
# pplt.rc.reset()  # uncomment for second run
plt.rcParams['font.size'] = 40
plt.rcParams['figure.dpi'] = 200
plt.rcParams['mathtext.default'] = 'it'

fig, ax = plt.subplots(figsize=(6, 4))
ax.axison = False
ax.text(.4, .7, 'normal', ha='right')
ax.text(.6, .7, 'italic', style='italic')
ax.text(.4, .3, r'$\mathrm{\alpha \beta \gamma \theta \pi}$', ha='right')
ax.text(.6, .3, r'$\alpha \beta \gamma \theta \pi$')
```

Without proplot settings:

![tmp_matplotlib](https://user-images.githubusercontent.com/19657652/149468262-0cb10e7b-6820-4813-ac80-ff8293ed9e5c.png)

With proplot settings:

![tmp_proplot](https://user-images.githubusercontent.com/19657652/149468265-2ec119ad-0a02-49db-8757-4bbc660cd832.png)

They are indeed different -- it seems TeX Gyre Heros is still being used for math, but since we set `rc['mathtext.default'] = 'it'`, it should be falling back to `rc['mathtext.fontset'] = 'dejavusans'`. Will try to figure this out another day.

Also will consider using a more math-friendly font as the default math text in the next proplot version. I could try `mathtext.fontset: stixsans` or try building a custom math text with e.g. Fira Math using the following settings:

```python
mathtext.default: it
mathtext.fontset: custom
mathtext.bf:  Fira Math:bold
mathtext.it:  Fira Math:italic
mathtext.rm:  Fira Math
mathtext.sf:  Fira Math
```

Seems that `stixsans` is the only other built-in sans-serif font that can be used as a mathtext other than `dejavusans`, and I'd really like to avoid using DejaVu fonts, so if I can't get Fira Math to work I'll try that.

**Comment by lukelbd** [comment]
And I finally remembered what I was thinking when I implemented this behavior: The idea was that the math text and string text should always be the same font, or else it could look "ugly". So, users would be expected to change the plot-wide font to something more suitable for math if need-be, e.g. with `pplt.rc['font.name'] = 'Fira Math'`.

However, as you've shown, this is kind of frustrating / unexpected -- the "aesthetic" benefits of forcing everyone to use the same font set for math and non-math text are outweighed by the practical issue that new proplot users are getting ugly math equations out-of-the-box. So, I will indeed remove this behavior.

**Comment by lukelbd** [comment]
Ok, I've thought about this some more, and despite my last comment, I think I'll stick with `pplt.rc['mathtext.fontset']` set to `'custom'`. I looked closer at some more examples with the new defaults, and things like tick labels formatted with `pplt.SciFormatter` or pi-markers, and even simple expressions, look plain weird with clashing non-math and math fonts.

However, I do agree with you that math should be in italics by default, so I'll also change `pplt.rc['mathtext.default']` from `'regular'` back to `'it'` (like in matplotlib). The trouble is, I'd really really like to figure out how to make matplotlib use the *current* font in *italics*, i.e. something like `pplt.rc['mathtext.default'] = 'regular:it'`. It seems this is not currently possible with public methods, but I'll see if I can figure out some workaround using the mathtext module.

**Comment by lukelbd** [comment]
#323 sets `rc['mathtext.default'] = 'it'` and uses the currently active font for math text by default rather than the global sans-serif font (meaning `rc['font.name] = 'font'` will also update the math text).
