### ISSUE TITLE
Typo in docs?

### ISSUE THREAD

**Issue by lkugler** [lukelbd/proplot#330]
Hi, 
Thank you for your amazing work.

I think the first example on page https://proplot.readthedocs.io/en/stable/basics.html should use 
`pplt.subplots()` instead of `pplt.subplot()`, right?

There is figure.subplot() but no pplt.subplot().

**Comment by lukelbd** [comment]
Np -- you're not blind, I think you were looking at the "latest" version on https://proplot.readthedocs.io/en/latest/basics.html! I add a `pplt.subplot` command that returns a single figure and subplot instead of a singleton [`SubplotGrid`](https://proplot.readthedocs.io/en/latest/api/proplot.gridspec.SubplotGrid.html#proplot.gridspec.SubplotGrid) of subplots. I find the latter can be a little annoying sometimes.

**Comment by syrte** [comment]
Great to have `pplt.subplot`! I'm a bit tired of typing `pplt.figure` every time.

BTW, I didn't find `pplt.subplot` in my proplot installed via conda. 
In the end, I got it by manually pip install it from github.

**Comment by lukelbd** [comment]
Yep `pplt.subplot` will be on pip/conda in the next release. Btw you can also use `fig, ax = pplt.subplots()` (note the `s`) and then proceed like normal with e.g. `ax.plot()`, `ax.contour`, `ax.format()`, etc. It's just that `ax` is a singleton `SubplotGrid`, which is a little strange/counterintuive ([this page of the docs](https://proplot.readthedocs.io/en/latest/basics.html#Multiple-subplots) has more on `SubplotGrid`s).

**Comment by syrte** [comment]
Thanks a lot for the tips!
