### ISSUE TITLE
axis limits come out reversed a lot

### ISSUE THREAD

**Issue by beckermr** [lukelbd/proplot#334]
### Description

Right now in many cases, the plot limits come out reverse (e.g., the x-axis goes from 1 to -4 instead of -4 to 1).

### Steps to reproduce

A "[Minimal, Complete and Verifiable Example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)" will make it much easier for maintainers to help you.

```python
import proplot as pplt
import numpy as np

rng = np.random.RandomState(seed=10)
x = rng.uniform(size=1000)*4 - 6
y = rng.uniform(size=1000)*2 + 6

fig, axs = pplt.subplots()
axs.hexbin(x, y)
```

**Expected behavior**: axis limits numerically ordered (should be -6 to -2)

**Actual behavior**: came out reversed (-2 to -6)

### Equivalent steps in matplotlib

Please try to make sure this bug is related to a proplot-specific feature. If you're not sure, try to replicate it with the [native matplotlib API](https://matplotlib.org/3.1.1/api/index.html). Matplotlib bugs belong on the [matplotlib github page](https://github.com/matplotlib/matplotlib).

```python
import matplotlib.pyplot as plt
import numpy as np

rng = np.random.RandomState(seed=10)
x = rng.uniform(size=1000)*4 - 6
y = rng.uniform(size=1000)*2 + 6

fig, axs = plt.subplots(nrows=1, ncols=1)
axs.hexbin(x, y)
```

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.

3.5.0
0.9.5

**Comment by lukelbd** [comment]
This is related to #300 (also documented on [this page](https://proplot.readthedocs.io/en/latest/1dplots.html#Data-arguments)). Proplot automatically reverses the axis when it detect "dependent" variable coordinates and the axes were not previously fixed -- however this behavior should definitely be disabled for `hexbin` and `hist2d`, and it looks like this used to be disabled for `hist` and `histh` but the fix implemented by #191 is now obsolete.

I'll fix this later today.

Note also that the #300 fix make this feature more conservative; for example when passing stuff to `ax.plot(x, y)` an axis will only be reversed if 1) the x limits were not previously fixed with e.g. `set_xlim` and 2) the x coordinates are *monotonically decreasing* rather than simply having a negative initial step size.

**Comment by beckermr** [comment]
Thank you!

**Comment by lukelbd** [comment]
Fixed by https://github.com/lukelbd/proplot/commit/275bf30b74aba6ddd9573398ebab1f252e467bf3. Here's an example:

```python
fig, axs = pplt.subplots(ncols=2, share=False)
x = np.sort(np.random.rand(100) * 100)
x = x[::-1]
axs[0].hist(x)
axs[1].hexbin(x, x)
print(pplt.internals.inputs._is_descending(x))
```

Result is `True` but axes are not reversed:

![iTerm2 dtQmy4](https://user-images.githubusercontent.com/19657652/152428610-281e320a-7d89-4142-86ff-7f6acfa749b6.png)

**Comment by beckermr** [comment]
Thank you! Looking forward to a release with the patch!
