### ISSUE TITLE
Map projection gridlines are layered much too high

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#61]
For some reason, it seems like the `zorder` layer of the grid lines added to a map projection is really high. I.e, they are prioritized to be layered on top of most other things. This is being prioritized here I think:

https://github.com/lukelbd/proplot/blob/7132b407d5ed9b777f28f3a4c15564321f87ec95/proplot/axes.py#L2952

Perhaps there can be an rc config option called `proplot.rc['geogrid.zorder']` or something like that. Here's what happens currently with the default:

```python
import proplot as plot
plot.rc['land.color'] = '#d3d3d3'

f, ax = plot.subplots(proj='spstere')

ax.text(0, 0, 'test', color='k')

ax.format(land=True, boundinglat=-40)
```

<img width="209" alt="Screen Shot 2019-10-31 at 3 02 31 PM" src="https://user-images.githubusercontent.com/8881170/67985909-7d552b80-fbef-11e9-991e-527441443edc.png">

And how I have to hack it so my continents are above my grid lines and my text doesn't get contaminated:

```python
import cartopy.feature as cfeature
f, ax = plot.subplots(proj='spstere')

ax.add_feature(cfeature.LAND, color='#d3d3d3', zorder=5)
ax.text(0, 0, 'test', color='k', zorder=6)

ax.format(boundinglat=-40)
```

<img width="236" alt="Screen Shot 2019-10-31 at 3 02 33 PM" src="https://user-images.githubusercontent.com/8881170/67985916-82b27600-fbef-11e9-8b50-07dbdf6d8bb4.png">

**Comment by bradyrx** [comment]
This could be an aesthetics preference between an oceanographer and atmospheric scientist :) Maybe there's a smooth global config to set the priority of layering. E.g. `proplot.rc.geolayering` and you set preference of gridlines vs. land/coastline stuff. And text always goes above those.

**Comment by lukelbd** [comment]
Definitely will address this.

There's a [axes.axisbelow](https://matplotlib.org/3.1.1/tutorials/introductory/customizing.html?highlight=axisbelow) rcParam that controls whether ticks/gridlines appear below everything, above everything, or above lines but below patches. I think `geogrid` gridlines should support this setting, and as for geographic elements, can add `land.axisbelow`, `coast.axisbelow`, etc. settings (or maybe just `land.below`, `coast.below`). And I think instead of `'lines'` as the intermediate option, I will use `'grid'` -- so ``True`` is below everything, ``'grid'`` is above everything but below gridlines, and ``False`` is above everything (the default).

 also add the intermediate option `'grid'`, sort of like `'lines'`, where


 me before, and this also applies

-- this has occured to me before,  how to handle zorder with these geographic patch elements,
