### ISSUE TITLE
Additional color maps

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#7]
@lukelbd, some more perceptually uniform colormaps for you to add if you'd like: http://www.fabiocrameri.ch/colourmaps.php

These were suggested to me (and designed by) Fabio Crameri in this thread: https://twitter.com/rileyxbrady/status/1046841027565215749

**Comment by lukelbd** [comment]
Thanks for the tip! They look great; will certainly add them.

**Comment by bradyrx** [comment]
Another good resource is https://sciviscolor.org/home/colormaps/. They've got some interesting nested sequential colormaps in there.

**Comment by lukelbd** [comment]
Just added the maps from SciVisColor and Fabio Crameri's website :). Also added the [CET](https://peterkovesi.com/projects/colourmaps/) colormaps, [Kenneth Moreland's](http://www.kennethmoreland.com/color-advice/) colormaps, and colormaps posted on the [Los Alamos Laboratory](https://datascience.lanl.gov/colormaps.html) website.

Here's a [pdf](https://github.com/lukelbd/proplot/files/2878275/colormaps.pdf) showcasing everything. They are all standardized so that diverging maps go from "cool" colors to "warm" colors, and so that sequential colormaps go from light to dark.

These appear to be almost all the scientific colormaps on the web (after googling "scientific colormaps"). I also found this ["colorcet"](https://github.com/pyviz/colorcet) Github repo, but IMHO none of the maps there are very unique/aesthetically pleasing.

Loading all of these maps takes 0.3s on my machine (the `register_cmaps()` function), which isn't great but is probably fine since the import only needs to be done once.

**Comment by bradyrx** [comment]
@lukelbd, wohoo, thanks for the implementations! Now I can spend more time tweaking color bars. Agreed on colorcet.

cpt-city (http://soliton.vm.bytemark.co.uk/pub/cpt-city/) is a famous one in the GMT community. Don't go down that rabbit hole as another color fiend.... there's hundreds and hundreds. But it's fun to scroll through.

> P.S. Thesis is done, so should get around to the other issues soon.

Congrats! Looking forward to the fixes, will let me move fully over to proplot.

**Comment by lukelbd** [comment]
> http://soliton.vm.bytemark.co.uk/pub/cpt-city/

...I may pretend I didn't see that lol. P.S. the [latest commits](https://github.com/lukelbd/proplot/commits/master) clean things up a bit, removes some of the less appealing CET maps. New PDF summary is [here](https://github.com/lukelbd/proplot/files/2881551/colormaps.pdf).
