### ISSUE TITLE
Order, orientation -> transpose ?

### ISSUE THREAD

**Issue by stefraynaud** [lukelbd/proplot#72]
The `orientation` keyword is used to transpose 1d plots and make them vertical.

In the same way, the `order` keyword is used in 2D plots to change the way dims are interpreted.
https://github.com/lukelbd/proplot/blob/591dac72fd33124b793e6d1e37e297005196a633/proplot/wrappers.py#L410
I'm not sure this is crucial since you always have to check the consistency between coordinates and data. In addition, this latter keyword can be confused with the matplotlib keyword. Is this one no longer accessible?

Don't you think a global `transpose` keyword would be more appropriate, for both 1D and 2D plots? For 2D plots, a value like "auto" would even try to guess the appropriate orientation depending on coordinates variations along dimensions, and potentially, attributes (lon, lat, time, etc....).

**Comment by lukelbd** [comment]
Makes sense to me. Note `order` [derives from numpy](https://numpy.org/devdocs/reference/generated/numpy.ravel.html), was just trying to go with their conventions. Want to submit a PR? I can also get to it sometime in December.

Also since you seem to be digging into these wrapper functions, keep an eye on #45 -- wrappers will soon be broken up into private helper functions, applied to dedicated `ax.plot`, `ax.contour`, etc. methods individually, and the documentation bits associated with each wrapper will be automatically embedded in the `ax.plot`, `ax.contour`, etc. methods using matplotlib's [docstring interpolation](https://matplotlib.org/3.1.1/devel/documenting_mpl.html#keyword-arguments).

**Comment by lukelbd** [comment]
I've finally added `transpose` as an alternative to `order` (b90cac4).

I haven'ted added `transpose` for the 1D plotting commands but I decided I'd rather not -- the new paradigm is to use "horizontal" versions of each plotting command (e.g. `plot`/`plotx`, `boxplot`/`boxploth`, etc. -- all of the new "horizontal" commands were motivated by matplotlib's `bar`/`barh` and `fill_between`/`fill_betweenx`).
