### ISSUE TITLE
y-axis doesn't like very small numbers

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#9]
The default y-axis tick labeling gets messed up when you go below 10^-3 for decimals.

```python
A = np.random.rand(60) / 100
# labeling doesn't work
f, ax = plot.subplots(axwidth=4, aspect=4)
ax.plot(A)
# labeling works
f, ax = plt.subplots(figsize=(6,1.5))
ax.plot(A)
```

Since default matplotlib handles this, it seems like a bug with your custom y-tick labeling.

`proplot`:

![image](https://user-images.githubusercontent.com/8881170/53041330-eff6f000-3440-11e9-8159-6a7156a409c2.png)

`matplotlib`:

![image](https://user-images.githubusercontent.com/8881170/53041334-f2594a00-3440-11e9-8600-5bf712ce3ace.png)

**Comment by bradyrx** [comment]
Current workaround is this, although not desirable. Might be helpful for fixing:

```python
A = np.random.rand(60) / 100
ticks = np.linspace(0, 0.01, 6)
labs = list(map(str, ticks))
f, ax = plot.subplots(axwidth=4, aspect=4)
ax.plot(A)
ax.format(yticks=ticks, yticklabels=labs)
```

![image](https://user-images.githubusercontent.com/8881170/53041662-c7232a80-3441-11e9-87c4-2f77c9698609.png)

**Comment by lukelbd** [comment]
Thanks for pointing that out. I had changed the tick label formatting because I wanted to remove trailing zeros on decimals. Now instead of using [`FuncFormatter`](https://matplotlib.org/api/ticker_api.html#matplotlib.ticker.FuncFormatter) (which caused a bunch of problems), I subclass the default [`ScalarFormatter`](https://matplotlib.org/api/ticker_api.html#matplotlib.ticker.ScalarFormatter) directly.

Removing trailing zeros is just my preference; will see if others don't like it, and if so disable it.

**Comment by lukelbd** [comment]
Decided to add a new rc setting called ``axes.formatter.zerotrim``, so trimming zeros can now be disabled.

**Comment by bradyrx** [comment]
@lukelbd , I'd suggest setting `axes.formatter.zerotrim` globally to False. Note that this will trim trailing zeros off of years too!

![screen shot 2019-02-28 at 7 43 58 pm](https://user-images.githubusercontent.com/8881170/53612837-4b3b8780-3b91-11e9-8308-8f37a939e897.png)

**Comment by lukelbd** [comment]
Yeah, that was just a simple regex mistake -- noticed it earlier, it's
fixed now. Am going to push that + a bunch of bugfixes soon; I went through
the demos as you suggested. My apologies for pushing so much broken code!
Should have checked earlier. Once version 1.0 is released, I'll be more
methodical about testing.
